from enum import Enum

# import pandas as pd
from PyQt5.QtGui import QFontDatabase
import os
import sys

import os
import sys
from pathlib import Path

# 定义路径
# config_dir = Path("player_info")

# # 如果目录不存在，就创建（包括父目录）
# config_dir.mkdir(parents=True, exist_ok=True)
debug: bool = False
debug: bool = True


def appdata_path(relative_path=""):
    """
    获取可写的用户数据目录路径
    用于保存配置、token、日志等可写文件
    """
    if debug:
        return relative_path  # 调试状态

    if sys.platform == "win32":
        base = Path(os.environ["APPDATA"])  # C:\Users\...\AppData\Roaming

    app_path = base / "PhiFilterTool"
    # app_path.mkdir(parents=True, exist_ok=True)  # 自动创建目录
    path_str = str(app_path / relative_path)
    file_path = Path(app_path / relative_path)
    print(f"这里的文件路径是:{file_path}")
    file_path.parent.mkdir(parents=True, exist_ok=True)
    if not file_path.exists():
        file_path.touch(exist_ok=True)  # 创建空文件
        print(f"Created file: {app_path / relative_path}")
    return path_str


def resource_path(relative_path):
    """
    获取打包后资源的正确路径
    用法: resource_path("images/avatar/1.png")
    """
    if debug:
        base_path = os.path.abspath(".")
    else:
        # PyInstaller 会创建临时文件夹，并把路径存入 sys._MEIPASS
        base_path = sys._MEIPASS
    return os.path.join(base_path, relative_path)


def log_write(text: str):
    with open(appdata_path(LOG_PATH), "a+", encoding="utf-8") as f:
        f.write(text + "\n")


class score_level_type(Enum):
    F = "F"
    C = "C"
    B = "B"
    A = "A"
    S = "S"
    V = "V"
    VFC = "蓝V"
    phi = "phi"


# 默认路径
# 整个文件的相对路径前缀
if debug:
    FILE_PATH = "projects/PhiFilterTool/"
else:
    FILE_PATH = ""

# 主文件夹下的文件可以直接写
CODE_PATH = FILE_PATH + "main_code.py"

# 固定的运行依赖文件夹
DEPENDENCES_PREPATH = FILE_PATH + "dependences/"

DIFFICULTY_PATH = DEPENDENCES_PREPATH + "difficulty.tsv"  # 各个歌曲难度文件
INFO_PATH = DEPENDENCES_PREPATH + "info.tsv"  # 组合名称与拆分名称对应关系文件
AVATAR_PATH = DEPENDENCES_PREPATH + "avatar.txt"  # 头像名称
NOTE_COUNT_PATH = (
    DEPENDENCES_PREPATH + "note_count.csv"
)  # 每个歌曲及难度对应的各种键型数量及总合
DEFUALT_COMMENT = DEPENDENCES_PREPATH + "defualt_comment.csv"  # 空白简评文件
DEFUALT_GROUP = DEPENDENCES_PREPATH + "defualt_group.csv"

UPDATE_PREPATH = DEPENDENCES_PREPATH + "update/"
OUTPUT_PATH = UPDATE_PREPATH + "output.txt"

# 字体文件
FONT_PREPATH = DEPENDENCES_PREPATH + "font/"

EN_FONT1_PATH = FONT_PREPATH + "Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf"
NUM_FONT1_PATH = FONT_PREPATH + "Share_Tech_Mono/ShareTechMono-Regular.ttf"
# CHI_FONT1 = FONT_PREPATH + "ZCOOLKuaiLe/ZCOOLKuaiLe-Regular.ttf"
CHI_FONT1_PATH = resource_path(
    FONT_PREPATH + "Source Han Sans & Saira Hybrid-Regular #5446.ttf"
)

FONT_FAMILY = {}
font_id = QFontDatabase.addApplicationFont(CHI_FONT1_PATH)
if font_id < 0:
    FONT_FAMILY["chi"] = "仿宋"
    print("中文字体加载失败！ 已切换为仿宋")
else:
    font_family = QFontDatabase.applicationFontFamilies(font_id)[0]
    FONT_FAMILY["chi"] = font_family


# 玩家信息(player_info)文件夹下文件的路径前缀
PLAYER_INFO_PREPATH = FILE_PATH + "player_info/"

# TOKEN_PATH = PLAYER_INFO_PREPATH + "session_token.txt"  # 玩家session_token存储路径
TOKEN_PATH = "session_token.json"  # 玩家session_token存储路径
LOG_PATH = "PhiFilterTool_log.txt"  # 日志文件
SETTING_PATH = "PhiFilterTool_setting.json"  # 玩家设置

GROUP_PATH = "group.csv"  # 玩家自定义分组信息存储路径
COMMENT_PATH = "comment.csv"  # 玩家自定义简评信息存储路径

# 图片素材(images)文件夹下文件的路径前缀
IMAGES_PREPATH = FILE_PATH + "images/"

# 头像图片路径前缀
AVATER_IMG_PREPATH = IMAGES_PREPATH + "avatar/"

# 各种小图标
ICON_PREPATH = IMAGES_PREPATH + "icons/"

RESET_PATH = ICON_PREPATH + "reset.png"
SAVE_ICON_PATH = ICON_PREPATH + "save.png"
FILTER_ICON_PATH = ICON_PREPATH + "filter.png"
FILTER_AGAIN_ICON_PATH = ICON_PREPATH + "filter_again.png"
QRCODE_EMPTY_IMG_PATH = ICON_PREPATH + "QRcode_empty.jpg"

# 各个评级的图标
SCORE_LEVEL_ICONS_PREPATH = ICON_PREPATH + "score_level_icons/"

SCORE_LEVEL_PATH = {
    score_level_type.F: SCORE_LEVEL_ICONS_PREPATH + "F.png",
    score_level_type.C: SCORE_LEVEL_ICONS_PREPATH + "C.png",
    score_level_type.B: SCORE_LEVEL_ICONS_PREPATH + "B.png",
    score_level_type.A: SCORE_LEVEL_ICONS_PREPATH + "A.png",
    score_level_type.S: SCORE_LEVEL_ICONS_PREPATH + "S.png",
    score_level_type.V: SCORE_LEVEL_ICONS_PREPATH + "V.png",
    score_level_type.VFC: SCORE_LEVEL_ICONS_PREPATH + "VFC.png",
    score_level_type.phi: SCORE_LEVEL_ICONS_PREPATH + "phi.png",
}

# 各种背景
BACKGROUND_IMG_PREPATH = "background/"
READONLY_BACKGROUND_IMG_PREPATH = IMAGES_PREPATH + "background/"

SONG_CARD_BACKGROUND = {  # 用途 作为背景区分不同难度 表示玩家挑战模式的等级
    "EZ": READONLY_BACKGROUND_IMG_PREPATH + "green-EZ.png",
    "HD": READONLY_BACKGROUND_IMG_PREPATH + "blue-HD.png",
    "IN": READONLY_BACKGROUND_IMG_PREPATH + "red-IN.png",
    "AT": READONLY_BACKGROUND_IMG_PREPATH + "gold-AT.png",
    "white": READONLY_BACKGROUND_IMG_PREPATH + "white.png",
    "colorful": READONLY_BACKGROUND_IMG_PREPATH + "colorful.png",
}

# 曲绘
ILLUSTRATION_PREPATH = IMAGES_PREPATH + "illustration/"

# 可作为筛选依据的属性
FILTER_ATTRIBUTION_LIST: list[str] = [
    "acc",
    "单曲rks",
    "得分",
    "定数",
    "评级",
    "难度",
    "曲名",
    "曲师",
    "谱师",
    "画师",
    # "分组",
    # "简评",
]

# 数值类比较
NUMERIC_COMPARATORS: list[str] = [
    "大于",
    "大于等于",
    "小于",
    "小于等于",
    "等于",
    "不等于",
]

# 精确 模糊比较
LOGICAL_OPERATORS: list[str] = ["等于", "不等于", "包含", "不包含"]

# ACG图片获取API
ACG_PPIMAGE_URL = "https://www.loliapi.com/acg/pp/"  # 头像获取
ACG_IMAGE_URL = "https://www.loliapi.com/acg/"  # 图片获取

MAX_LEVEL: float = 17.6  # 当前版本最高定数


# ---------------默认样式表获取---------------
def get_combobox_style(
    font_size: str = 23,
    font_family: str = FONT_FAMILY["chi"],
    max_width: str = 360,
    min_width: str = 360,
    min_height: str = 50,
    max_height: str = 50,
    border_radius: str = 7,
    background_color: tuple[str, str, str, str] = (255, 255, 255, 0),
):
    style = "ComboBox {\n"
    r, g, b, a = background_color
    style += f"""
    font-size: {font_size}px;
    font-family: "{font_family}";
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    border: 2px solid black;
    border-radius: {border_radius}px;
    background-color: rgba({r},{g},{b},{a});
    text-align: left;
    padding-left: 5px;
    """
    style += "}"
    return style


def get_button_style(
    max_width: str = 360,
    min_width: str = 360,
    min_height: str = 50,
    max_height: str = 50,
    font_family: str = FONT_FAMILY["chi"],
    font_size: str = 34,
    border_radius: str = 7,
    background_color: tuple[str, str, str, str] = (0, 159, 170, 1),
    color: str = "white",
):
    style = "PushButton {\n "
    r, g, b, a = background_color
    contain = f"""
    font-size: {font_size}px;
    font-family: "{font_family}";
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    border-radius: {border_radius}px;
    background-color: rgba({r},{g},{b},{a});
    color: {color};
    """
    style += (
        contain
        + """
        }
    PushButton:hover {
        background-color: #00CDCD;
    }
    PushButton:pressed {
        background-color: #00FFFF;
    }"""
    )
    return style


def get_label_style(
    font_size: str = 26,
    max_width: str = 0,
    min_width: str = 0,
    min_height: str = 0,
    max_height: str = 0,
    font_family: str = FONT_FAMILY["chi"],
    font_color: tuple[int, int, int, int] = (0, 0, 0, 1),
    background_color: tuple[int, int, int, int] = (255, 255, 255, 0),
    other: str = None,
):
    style = """QLabel {\n"""
    r, g, b, a = background_color
    fr, fg, fb, fa = font_color
    style += f"""
    font-size: {font_size}px;
    font-family: '{font_family}';
    color: rgba({fr},{fg},{fb},{fa});
    background-color: rgba({r},{g},{b},{a});
    """

    if max_width > 0:
        style += f"max-width: {max_width}px;\n"
    if min_width > 0:
        style += f"min-width: {min_width}px;\n"
    if min_height > 0:
        style += f"min-height: {min_height}px;\n"
    if max_height > 0:
        style += f"max-height: {max_height}px;\n"

    style += (other if other is not None else "") + "}"
    return style


def get_input_box_style(
    max_width: str = 300,
    min_width: str = 300,
    min_height: str = 60,
    max_height: str = 60,
    font_family: str = FONT_FAMILY["chi"],
    font_size: str = 28,
    border_radius: str = 7,
    background_color: tuple[str, str, str, str] = (255, 248, 220, 1),
):
    style = "LineEdit {\n "
    r, g, b, a = background_color
    style += f"""
    font-size: {font_size}px;
    font-family: "{font_family}";
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    border-radius: {border_radius}px;
    background-color: rgba({r},{g},{b},{a});
    """
    style += "}"
    return style


def get_switch_button_style(
    font_family: str = FONT_FAMILY["chi"],
    max_width: str = 210,
    min_width: str = 210,
    min_height: str = 30,
    max_height: str = 30,
):
    style = "SwitchButton {\n"
    style += f"""
    font-family: "{font_family}";
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    """
    style += "}"
    return style


# ------------------ 缓存内容 --------------------
# 曲名
SONG_NAME_LIST: list[str] = [
    """Glaciaxion""",
    """Eradication Catastrophe""",
    """Credits""",
    """Dlyrotz""",
    """Engine x Start!! (melody mix)""",
    """光""",
    """Winter ↑cube↓""",
    """Cipher : /2&//<|0""",
    """混乱-Confusion""",
    """FULi AUTO SHOOTER""",
    """HumaN""",
    """[PRAW]""",
    """Pixel Rebelz""",
    """Cereris""",
    """Non-Melodic Ragez (MUG Edit)""",
    """Sultan Rage""",
    """Class Memories""",
    """-SURREALISM-""",
    """Bonus Time""",
    """ENERGY SYNERGY MATRIX""",
    """NYA!!! (Phigros ver.)""",
    """JunXion Between Life And Death(VIP Mix)""",
    """cryout""",
    """Reimei""",
    """尊師 ～The Guru～""",
    """Spasmodic""",
    """Leave All Behind""",
    """Colorful Days♪""",
    """micro.wav""",
    """重生""",
    """NO ONE YES MAN""",
    """望影の方舟Six""",
    """Igallta""",
    """Clock Paradox""",
    """Chronologika""",
    """Nick of Time""",
    """Chronomia""",
    """Chronos Collapse - La Campanella""",
    """Rrhar\'il""",
    """Crave Wave""",
    """The Chariot ~REVIIVAL~""",
    """Luminescence""",
    """Retribution""",
    """DESTRUCTION 3,2,1""",
    """Distorted Fate""",
    """Doppelganger""",
    """もぺもぺ""",
    """MARENOL""",
    """萤火虫の怨""",
    """万吨匿名信""",
    """风屿""",
    """dB doll""",
    """Dash""",
    """云女孩""",
    """Drop It""",
    """RIPPER""",
    """Aphasia""",
    """开心病""",
    """華灯爱""",
    """Find_Me""",
    """Sein""",
    """狂喜蘭舞""",
    """Sparkle New Life""",
    """Khronostasis Katharsis""",
    """Snow Desert""",
    """Burn""",
    """Aleph-0""",
    """Next Time""",
    """Rubbish Sorting""",
    """Another Me""",
    """mechanted""",
    """life flashes before weeb eyes""",
    """Break Through The Barrier""",
    """Chronostasis""",
    """Dead Soul""",
    """Infinity Heaven""",
    """Disorder""",
    """CROSS†SOUL""",
    """Speed Up!""",
    """Magenta Potion""",
    """Get Back""",
    """Palescreen""",
    """GOODTEK""",
    """GOODBOUNCE""",
    """GOODWORLD""",
    """GOODFORTUNE""",
    """GOODRAGE""",
    """The Mountain Eater""",
    """Orthodox""",
    """End Me""",
    """Parallel Retrogression(Game Ver.)""",
    """Starduster""",
    """Electron""",
    """SIGMA""",
    """Hardcore Kwaya""",
    """Äventyr""",
    """Träne""",
    """雪降り、メリクリ""",
    """Cervelle Connexion""",
    """modulus""",
    """Wavetapper""",
    """大和撫子 -Wild Dances-""",
    """Eltaw""",
    """Initialize""",
    """桜樹街道""",
    """Get Ready!! """,
    """volcanic""",
    """Better Graphic Animation""",
    """XING""",
    """Final Step!""",
    """Cthugha""",
    """With You""",
    """Unorthodox Thoughts""",
    """Apocalyptic""",
    """游园地""",
    """energy trixxx""",
    """Nhelv""",
    """-Arkhei-""",
    """Kerberos""",
    """ρars/ey""",
    """Concvssion""",
    """ジングルベル(Jingle Bell)""",
    """Time to Night Sky (feat. Lee Yu Jin)""",
    """HAZARD""",
    """Another Me""",
    """Don\'t Never Around""",
    """RESSiSTANCE""",
    """Dreamland""",
    """Another Round""",
    """996""",
    """Future Mind""",
    """Luminescent""",
    """FULi AUTO BUSTER""",
    """I Must Say No""",
    """opia""",
    """Apocalypse""",
    """Protoflicker""",
    """Horizon Blue""",
    """You are the Miserable""",
    """Stasis""",
    """いざ、参ります""",
    """月下缭乱""",
    """On And On!!""",
    """DataErr0r""",
    """Shadow""",
    """心之所向""",
    """inferior""",
    """c.s.q.n.""",
    """Brave Notes""",
    """盏茗""",
    """青芽""",
    """Eternal Snow""",
    """Rainy Season""",
    """El Condor Pasa (Phigros Edit)""",
    """Break Over""",
    """Believe Light (feat. 果丸哒呦)""",
    """Pont des souvenirs""",
    """青丘""",
    """瓷岁""",
    """Feast远东之宴""",
    """インフェルノシティ""",
    """Upshift""",
    """Poison AND÷OR Affection""",
    """Random""",
    """零號車輛""",
    """Now Is The Time, Do It""",
    """Bougainvillea""",
    """神話""",
    """El último baile""",
    """Trojan""",
    """Temporal Shifting""",
    """Ad astra per aspera""",
    """A journey to the moonlight""",
    """Rainy Heart""",
    """Realms""",
    """ぱぴぷぴぷぴぱ""",
    """Triumph & Regret""",
    """S.A.T.E.L.L.I.T.E.""",
    """Dance with Silence""",
    """Labyrinth in Kowloon: Walled World""",
    """Compute It With Some Devilish Alcoholic Steampunk Engines""",
    """+ERABY+E CONNEC+10N""",
    """Diamond Eyes""",
    """Bitterblossom""",
    """Silence is Golden, Speech is Golden""",
    """Fractured Angel""",
    """Journey with You""",
    """Secret Illumination""",
    """Inverted World""",
    """月詠に鳴る""",
    """TECHNOPOLIS 2085""",
    """祈 -我ら神祖と共に歩む者なり-""",
    """bye""",
    """聖夜讃歌""",
    """ストレイソウル・アラウンド""",
    """Manifold Hypothesis""",
    """K.Moe (VIP)""",
    """G.V.N. (Glitter,Vomitus and Neon)""",
    """Crush BETA""",
    """Broken Sky""",
    """BRAIN HACKER""",
    """Xenolith""",
    """Artificial Existence""",
    """Indelible Scar""",
    """Antithese""",
    """PRAGMATISM -RESURRECTION-""",
    """Shine After""",
    """Bloom""",
    """幽世桔梗""",
    """千紫万紅""",
    """明鏡烈火""",
    """今天不是明天""",
    """Cuvism³""",
    """iL-Artifact""",
    """a truth seeker -Communication with Utopia will be lost-""",
    """Bounded Quietude""",
    """君往何处 (Quo Vadis)""",
    """暗夜苏醒 (REANIMATE)""",
    """Grimheart""",
    """Thrash force""",
    """Originally""",
    """黄金之城 (GOLD TOWN)""",
    """双重间谍 (Double Agent)""",
    """幻影鬼魅 (PLEASE)""",
    """Schadenfreude""",
    """Le temps perdu""",
    """Fixations Toward the Stars""",
    """valor/starcross""",
    """Comet""",
    """白と黒のバケモノ""",
    """Devotion""",
    """Kirakira Noel Story!!""",
    """Shelter""",
    """蝎虎天体 -Lacertid-""",
    """贝多芬祝福 (Beethoven Blessing)""",
    """インマイマインド""",
    """ニライカナイ (NiraicA_nai Mix)""",
    """Swing Skip Drop""",
    """宇宙残骸少女 (Cosmic Dusty Girl)""",
    """Resolver""",
    """Luminous Entities Lost Heart""",
    """KIZUNA Resolution""",
    """AbsoluTe disoRdeR""",
    """Aphrodite\'s Child (short ver.)""",
    """DevIAtiOn (short ver.)""",
    """NO x""",
    """Alice in a xxxxxxxx""",
    """Radiance""",
    """Diamond Dust""",
    """Stardust:RAY""",
    """Frozen Heart""",
    """Helios""",
    """Flutter Echo""",
    """Re：birth""",
    """Avataar ~Reincarnation of Kalpa~""",
    """雪降り ~雪が降っている~""",
    """Retribution ~ Cycle of Redemption ~ """,
    """アンビバレンス""",
    """Komplexe""",
    """sølips""",
    """QZKago Requiem""",
    """Ποσειδών""",
    """WATER""",
    """Miracle Forest (VIP Mix)""",
    """MOBILYS""",
    """Lyrith -迷宮リリス-""",
    """Demiurge""",
    """Demonkin""",
    """Re_Nascence (Psystyle Ver.) """,
    """Ark""",
    """After Dawn""",
    """INFiNiTE ENERZY -Overdoze-""",
    """Khalid""",
    """Quantum Hyperspace""",
    """Freaky Undulations ~Noble Knights of Tune~""",
    """PANIC PARADISE""",
    """Re：End of a Dream""",
    """心の記憶""",
    """Spotlight""",
    """NightTheater""",
    """Ramification""",
    """Der Richter""",
    """ATHAZA""",
]

# 曲师
COMPOSER_LIST: list[str] = [
    """SunsetRay""",
    """NceS""",
    """Frums""",
    """Likey""",
    """CrossingSound""",
    """姜米條""",
    """Ctymax feat. NceS""",
    """Tetrajectory feat. Ctymax""",
    """Only My Black Score""",
    """MYUKKE.""",
    """SOTUI""",
    """Bluewind""",
    """Normal1zer""",
    """SunsetRay/NceS""",
    """Normal1zer""",
    """MonstDeath""",
    """Antistar feat. Ctymax""",
    """Itsuki""",
    """Megalo_PaleWhite""",
    """Tanchiky""",
    """FLuoRiTe/姜米條""",
    """1N6Fs""",
    """Ju_E""",
    """影虎。""",
    """rider""",
    """姜米條☆颶風 ~ ♫元力上人♫""",
    """rider""",
    """P4koo feat. つゆり花鈴""",
    """dandeless""",
    """姜米條""",
    """MYUKKE.""",
    """Se-U-Ra""",
    """Se-U-Ra""",
    """WyvernP""",
    """Hundotte""",
    """P4koo""",
    """Lime""",
    """SunsetRay""",
    """Team Grimoire""",
    """LandRoot""",
    """Attoclef""",
    """米虾Fomiki & 初云CLoudie""",
    """nm-y & Kry.exe""",
    """Normal1zer vs. Broken Nerdz""",
    """Sakuzyo""",
    """LeaF""",
    """LeaF""",
    """LeaF""",
    """闫东炜""",
    """闫东炜""",
    """闫东炜""",
    """YUE.STEVEN/uen""",
    """小红Akane，李祥晖""",
    """符白牙/SiYFics""",
    """Asuka""",
    """Friedwav""",
    """闫东炜""",
    """闫东炜""",
    """闫东炜""",
    """K-forest""",
    """朔(Apo11o program vs. お月さま交響曲) ft. kuroa*×荒巻""",
    """LeaF""",
    """rider""",
    """Halv""",
    """WyvernP""",
    """NceS""",
    """LeaF""",
    """SaMZIng""",
    """Ctymax vs. NceS""",
    """Neutral Moon""",
    """rareguy""",
    """BilliumMoto""",
    """lixound""",
    """黒皇帝""",
    """Sound Souler""",
    """HyuN""",
    """HyuN feat. YURI""",
    """HyuN feat. Syepias""",
    """DarTokki""",
    """EmoCo.""",
    """CAP3""",
    """WyvernP feat. Madol""",
    """EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """Paul Bazooka""",
    """tokiwa""",
    """ZxNX as \"Delaina\"""",
    """Tetrajectory""",
    """Quree""",
    """ElousΛ.-FZ""",
    """Kry.exe""",
    """EnFr""",
    """Grand Thaw / Rigël Theatre""",
    """MALVA.""",
    """A-39""",
    """SCTL""",
    """PTB10""",
    """Frums""",
    """adaptor vs DRIVE.""",
    """Fl00t""",
    """iF""",
    """kozato snow""",
    """iF""",
    """DETRO a.k.a. ルゼ""",
    """ルゼ""",
    """ginkiha""",
    """Lime""",
    """USAO""",
    """Cashew""",
    """Joulez""",
    """Z ClaxX & SumaiLight""",
    """椒盐菠萝""",
    """KAH""",
    """Silentroom""",
    """Sera Amagi""",
    """Zris""",
    """siqlo""",
    """Halv""",
    """A-39/沙包P""",
    """HyuN & KLYDIX""",
    """Limpid""",
    """D_AAN""",
    """HAMA""",
    """ぐるたみん""",
    """z1on & kyrrin""",
    """Justin Dai""",
    """李化禹""",
    """Ray Nautica & Reku Mochizuki""",
    """Daison""",
    """MYUKKE.""",
    """TangJuan""",
    """rN""",
    """アリスシャッハと魔法の楽団""",
    """Silentroom""",
    """Nothing But Requiem feat. Aikapin & Chiyoko""",
    """t+pazolite""",
    """Maozon""",
    """U-ske feat. 棗いつき""",
    """月見静華 vs. LUNARiUM""",
    """ETIA. feat. Jenga""",
    """Cosmograph""",
    """姜米條&SumaiLight""",
    """姜米條""",
    """姜米條""",
    """Aoi""",
    """Turquoise(DRIVE.+Nota)""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """Abyss Idols""",
    """Abyss Idols""",
    """Plastic Fruits""",
    """K-forest""",
    """Scaler & Mestie & 果丸哒呦""",
    """VeetaCrush vs. [itsu(feat.itsu)]""",
    """BLACK 0""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """Ponchi♪ feat. はぁち""",
    """Iriss-Frantzz""",
    """LeaF""",
    """Sobrem × Silentroom""",
    """seatrus""",
    """Roy Mikelate""",
    """Jade""",
    """Pica & M2U""",
    """Θ""",
    """litmus*""",
    """Lure Rabbit & V!C""",
    """Rabbit House""",
    """Yesod""",
    """BelieverInYou(阿卡姆巫师)""",
    """Hinkik & A Himitsu""",
    """ころねぽち With 立秋""",
    """typeMARS""",
    """かめりあ""",
    """かめりあ""",
    """かめりあ""",
    """かめりあ""",
    """かめりあ""",
    """SYNTHETIC""",
    """imvi""",
    """NIWASHI""",
    """DJ Raisei""",
    """Iris""",
    """Yooh""",
    """ARForest""",
    """Feryquitous feat.藍月なくる""",
    """PRASTIK DANCEFLOOR""",
    """光吉猛修 VS 穴山大輔 VS Kai VS 水野健治 VS 大国奏音""",
    """DingerBox""",
    """A-39/沙包P""",
    """みーに""",
    """cybermiso feat. tigerlily""",
    """ZxNX""",
    """Salty Salt & Unfold33""",
    """shadow_bling""",
    """Jungo & MAX 3 feat. 刘佳宜Snow & 幻影刃shadow""",
    """SOMON""",
    """Tatsh""",
    """Jun Kuroda""",
    """Noah""",
    """Blacklolita""",
    """Laur""",
    """ADean & JocularACE""",
    """targ & 麻团qwq""",
    """Capchii feat. まるもこ""",
    """r0y vs. WABI""",
    """M-UE vs. Reku Mochizuki""",
    """PIKASONIC feat. 兰音Reine""",
    """Fl00t vs Halv""",
    """Link\'\'0""",
    """kuro""",
    """Finite Limit vs SiLiS""",
    """M2U""",
    """Warak""",
    """Puru""",
    """KAH vs. E0ri4""",
    """SNKS & Mizku""",
    """MEMME""",
    """Wav.AV""",
    """R300K""",
    """ZxNX""",
    """Daison""",
    """Foodbot""",
    """Lundy vs. Wyvren""",
    """CNHKSS feat. 符白牙""",
    """テヅカ""",
    """Connexio""",
    """Reku Mochizuki""",
    """MeatyRabbit & NceS""",
    """Cream vs. Daily天利""",
    """Nauts""",
    """レシオP""",
    """roop from STR""",
    """ミハイル""",
    """辻原一郎""",
    """Gomadare""",
    """NormalM feat. Usagi Denki""",
    """TAG""",
    """Acute Disarray""",
    """RUQOA""",
    """polysha""",
    """Juggernaut.""",
    """Nagiha""",
    """Nhato""",
    """Masahiro “Godspeed” Aoki""",
    """kanone vs. BlackY""",
    """A-39 / 沙包P""",
    """NOA(Cortrix) & BotaNya""",
    """Cansol""",
    """ああああ""",
    """Scarlette a.k.a CrYmson""",
    """AiSS w/ 夜輪 ft. 結月ゆかり""",
    """Ardolf vs. Daily天利""",
    """すりぃ×相沢""",
    """雄之助 feat. Sennzai""",
    """rintaro soma""",
    """t+pazolite""",
    """1112 vs. Star＊""",
    """A-39/沙包P""",
    """Rinth_live""",
    """Dachs""",
    """ユメミド""",
    """Rabpit""",
    """Forged Reigns""",
    """Rinth_live""",
    """kanoryo""",
    """S9ryne""",
    """Reku Mochizuki""",
    """Dolphin""",
    """D_AAN""",
    """Jehezukiel + KURORAK""",
    """DJ SHION.Y""",
    """uma vs. モリモリあつし""",
    """A-39/沙包P""",
    """Ardolf""",
    """わかどり""",
    """rareguy & Reina""",
    """Ωμεγα""",
    """LeaF""",
]

# 画师
DRAWER_NAME_LIST: list[str] = [
    """艾若拉""",
    """海产""",
    """Ctymax""",
    """DoublePian""",
    """赤芽""",
    """winder""",
    """翠冷兮""",
    """IvyTowers""",
    """L-sp4""",
    """ViscerA & Psycholine""",
    """CH""",
    """老张""",
    """艾是Abby""",
    """IvyTowers""",
    """cycats""",
    """笔记RE""",
    """xperz""",
    """喵n葵""",
    """笔记RE""",
    """Karameru""",
    """NEKO&海产""",
    """IvyTowers""",
    """Haight""",
    """英英英""",
    """1B""",
    """昔璃☆暴雨 ~ ♫危難聖帝♫""",
    """笔记RE""",
    """Doro-nyong & Ratif""",
    """snake.ribs""",
    """昔璃&TNiK""",
    """青鸟""",
    """鲸弑""",
    """Se-U-Ra""",
    """汉堡""",
    """幽灵星""",
    """青鸟""",
    """inukoro""",
    """老张""",
    """犀牛坨动画工坊""",
    """笔记RE""",
    """翠冷兮""",
    """子狼""",
    """NerSAN""",
    """rN""",
    """knife美工刀""",
    """海产""",
    """cycat""",
    """喵n葵""",
    """L-sp4""",
    """IvyTowers""",
    """cycats""",
    """何呵""",
    """艾是Abby""",
    """御坂果子""",
    """TNiK""",
    """何呵""",
    """笔记RE""",
    """昔璃""",
    """IvyTowers""",
    """YuKiMuMa""",
    """hideo""",
    """DoublePian""",
    """1B""",
    """utosao""",
    """knife美工刀""",
    """knife美工刀""",
    """Optie""",
    """叶藤""",
    """knife美工刀""",
    """IvyTowers""",
    """IvyTowers""",
    """百九十八""",
    """Xquid""",
    """Sand""",
    """Photonskyto""",
    """DoublePian""",
    """Nabom""",
    """knife美工刀""",
    """TNiK""",
    """NOISER""",
    """TNiK""",
    """GAMEBAKA""",
    """Ctymax feat. EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """Ctymax""",
    """Ctymax feat. EBIMAYO""",
    """START SEED""",
    """cycats""",
    """何呵""",
    """青鸟""",
    """IvyTowers""",
    """DoublePian""",
    """塔塔""",
    """EnFr""",
    """Grand Thaw / Rigël Theatre""",
    """しえろ""",
    """犀牛坨动画工坊""",
    """SCTL""",
    """geralt""",
    """百九十八""",
    """りゅうら""",
    """xperz""",
    """あおお/A-ZERO, morph""",
    """あおお/A-ZERO, morph""",
    """あおお/A-ZERO, morph""",
    """あおお/A-ZERO, morph""",
    """A-Zero Project""",
    """打雷打人（青鸟 modified）""",
    """谷地（青鸟 modified）""",
    """谷地（青鸟 modified）""",
    """ADZUKI""",
    """ASXX""",
    """佑木いずみ & Ctymax""",
    """CEM""",
    """手鞠鈴 & 自動車 原付""",
    """駿""",
    """Hachimitsu☆Boy""",
    """Eridani""",
    """出前 x nekomiya""",
    """汉堡""",
    """爱39的Konya""",
    """ZG""",
    """ZG""",
    """ZG""",
    """Arahosi""",
    """LINUS""",
    """海产""",
    """艾是Abby""",
    """笔记RE""",
    """Keiby.comics""",
    """鲸弑""",
    """cycats""",
    """cycats""",
    """rN @ 湯元画伯""",
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """緑風マルト""",
    """TNiK""",
    """わっふゑ""",
    """Photonskyto""",
    """御坂果子""",
    """笔记RE""",
    """群青kurara""",
    """Ctymax vs. TNiK feat. 出前""",
    """林语""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """Sak""",
    """Robin""",
    """青鸟""",
    """圆规compasses""",
    """圆规compasses""",
    """林语""",
    """BLACK 0""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """LESYEF & 藍瀬 まなみ""",
    """Iriss=Frantzz=s-don""",
    """笔记RE/海产""",
    """Harkiadel""",
    """2AI4wU4""",
    """青鸟""",
    """TNiK""",
    """mology (青鸟&V17AMax Modified)""",
    """mology (青鸟&V17AMax Modified)""",
    """Lapelristar (青鸟&V17AMax Modified)""",
    """mology (青鸟&V17AMax Modified)""",
    """Lyrebird Ferdinant (青鸟&V17AMax Modified)""",
    """汉堡""",
    """Sodhelium""",
    """圆规compasses""",
    """上倉エク""",
    """何呵""",
    """青鸟""",
    """林语""",
    """鲸弑""",
    """山崎团""",
    """猫箱Catbox feat. 祈莲""",
    """彗星 feat. 祈莲""",
    """鲸弑""",
    """Jerry & OsuMe65""",
    """OsuMe65""",
    """BTKCyber (青鸟 modified)""",
    """Juice Black (青鸟 modified)""",
    """Mechari (青鸟 modified)""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """海产""",
    """绀屋""",
    """伊恩 (青鸟 modified)""",
    """阿清 (青鸟 modified)""",
    """BTKCyber (青鸟 modified)""",
    """祈莲""",
    """笔记RE""",
    """午苔veeee~""",
    """SOMON""",
    """2AI4wU4""",
    """2AI4wU4""",
    """兜""",
    """釜飯轟々丸 + jht (Design: 祈莲)""",
    """シエラ (Design: 祈莲)""",
    """海里狄七 feat. 存艺""",
    """注射""",
    """瀬名""",
    """中本ひょうり""",
    """中本ひょうり""",
    """KiTA & 一击即溃""",
    """sikkari""",
    """Fl00t""",
    """rokopon""",
    """Hiro vs Zeth""",
    """LRAY (青鸟 modified)""",
    """MHK (青鸟 modified)""",
    """临时工 & 倪尔""",
    """自動車 原付 vs. GAMEBAKA""",
    """Keiby.comics""",
    """RM Design Team (青鸟 modified)""",
    """RM Design Team (青鸟 modified)""",
    """RM Design Team (青鸟 modified)""",
    """验光蒸鱼""",
    """子狼""",
    """AriaL [edited by Stelli]""",
    """AriaL & 57_dayo [edited by Stelli]""",
    """小黄鸡叽叽叽叽叽叽修复中""",
    """久世""",
    """Shimoruchiko""",
    """ナナシ""",
    """诡异童话""",
    """白 & 小鹏xpeng""",
    """RM Design Team (青鸟 modified)""",
    """すずか爆弾""",
    """3z""",
    """ディン""",
    """TOTOTO """,
    """Transendium""",
    """Transendium""",
    """Transendium""",
    """Kyuare & Wsx""",
    """Sin:cK for Immaculée Sekai""",
    """cala for Immaculée Sekai""",
    """cala for Immaculée Sekai""",
    """神居冰绘 feat. 祈莲""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """山山奇""",
    """Spectro""",
    """Taurell""",
    """QueseraGames Co., Ltd.""",
    """QueseraGames Co., Ltd.""",
    """Vios.NoFurry.git""",
    """死と花の大祭司(ʌᴉoƨმᴉϝ);;""",
    """SEGA (祈莲 modified)""",
    """SEGA (祈莲 modified)""",
    """SEGA (祈莲 modified)""",
    """SEGA (祈莲 modified)""",
    """老张""",
    """knife美工刀""",
    """L-sp4""",
    """わっふゑ""",
    """何呵""",
    """青鸟""",
    """Jeffery""",
    """Tsuioku""",
    """MOAI WORKS""",
    """月亮酱""",
    """knife美工刀""",
    """HAZUQU""",
    """sa1t""",
    """PEZZ feat. 祈莲 & CattoHato""",
    """百九十八""",
    """masiro vs. adaptor""",
    """爱39的Konya""",
    """NerSAN""",
    """青鸟""",
    """cokeAnut""",
    """森灵""",
    """御坂果子""",
]

# 谱师
CHARTER_LIST: list[str] = [
    """Su1fuR -All about YOU & ME-""",
    """Likey -For an old friend-""",
    """Stray Cat Around""",
    """Sparkle Ctymax fixed by 百九十八""",
    """AUTO. SHOOTER. fixed by Ctymax""",
    """Hardcore Barbaya""",
    """Burn Full Catcats vs. Ctymatch Girl""",
    """2B45524142592B45""",
    """Find_Ctymax fixed by 百九十八""",
    """Timi今天吃神马""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by Pcat""",
    """IMD_0b0110""",
    """NerSAN feat. Takanashi Rikko""",
    """RTH""",
    """百九十八 feat. NerSAN""",
    """無†極""",
    """P & U""",
    """Nothing But Ner & Pcat""",
    """撕裂者『Alloces vs. Shin』""",
    """Where are Ctymax and 阿爽?""",
    """Future BarbarXMT""",
    """StupiGGy fixed by 百九十八""",
    """inert COC""",
    """Su1fuRikko \"SouRce of the metaveRse\"""",
    """NerSAN feat. Pcat""",
    """StupiGGy -The Startline-""",
    """StupiGGy vs. 阿爽""",
    """R/kko""",
    """StupiGGy vs. 百九十八 ft. 野从""",
    """Rikko EXPERT Life:999""",
    """Eaimo vs. CtyNer dancing wildly""",
    """ƃuɐnɥs∀ .sʌ uoqsnɐ⅁""",
    """N.E.R.1.9.8.""",
    """Salt""",
    """jouR.ney to the end【COVERED】""",
    """Gausbon vs. XMT小咩兔""",
    """XMT小咩兔""",
    """XMT after BarbarNerSAN""",
    """B.A.R.B.A.R.I.A.N.E.R.M.A.N.""",
    """Salt & _鉄 inspired by 存在証明 [X]""",
    """兔咩小 VS 咩小兔 VS 小兔咩 VS 咩兔小 VS 兔小咩""",
    """RWND -p 16493:62786:92551""",
    """CN_115 as \"prediCameNt\"""",
    """RDRT -p 20:08:31""",
    """M3d1uM""",
    """Likey & Gausbon""",
    """Ner ~ See you next time ~""",
    """HCC!!!""",
    """Su1fuR""",
    """A.S.H.""",
    """亚树见希子 & 百九十八""",
    """NerSAN sipping XMTea""",
    """VikingNexus""",
    """右果_Ary""",
    """Likey underground""",
    """穿山甲-1""",
    """云正太""",
    """XMT as \"eX-MentalisT\"""",
    """Eastern Ailuropoda Gang""",
    """BlindForest""",
    """StuRmfeuer""",
    """Arenn Saki vs. NerSAN""",
    """Arenn Saki as \"myStery\"""",
    """Nothing But Uvernight""",
    """波""",
    """{Devastation,Destruction}""",
    """h.o.m.e.e.e.""",
    """Cluttler with ShelteR""",
    """Barbarianerman vs. Snorkel""",
    """De Fiance""",
    """Two skunks (Ctymax and 晨) in Africa shouting WAHHHHHH!""",
    """乱流に巻き込まれ""",
    """XMT, Encore after the end""",
    """Su1fuR vs. Simon_Axis""",
    """弧光""",
    """Pcat『Scatter』""",
    """∅""",
    """CN_115+TangScend""",
    """Rikko & 198""",
    """TangScend -Err0rederci-""",
    """光る星""",
    """BarbariaNERman vs. JKy""",
    """Sillyp""",
    """Min(C,t,y)""",
    """Pcat""",
    """One skunk (Ctymax) in Africa""",
    """Spy-Simon_Axis | Spy-騎士""",
    """B.B.M.""",
    """N-23""",
    """Ctymatch Girl""",
    """while(TangScend<=TangScend);""",
    """jeitie touches grass""",
    """Barbarianerman, Main theme within the somnium""",
    """JKy as \"Stray Cat\"""",
    """Cloud Catcats""",
    """{Demolition,Devastation,Destruction}""",
    """Jeitie & CorruptedEntity 『Hollow』""",
    """1÷98""",
    """Su1fuRikko × rN \"judgemeNt fRom the cataStRophy\"""",
    """Uvernight fixed by 百九十八""",
    """Ner & 198 from 「PHIGROS MOON」""",
    """Cty moyules""",
    """啊哒咔哟 & 小咩兔 & COC""",
    """Uvernight fixed by StR-1""",
    """vacant/stupiggy""",
    """TimiTini & HaraKuma""",
    """H.C.C. fixed by Barbarinerman""",
    """Arenn Saki vs. Catcats vs. 百九十八""",
    """Merry xmAS""",
    """Simon_Axis""",
    """Affection&memories \\\\// Salt & Simon_Axis""",
    """Swing Salt ♪""",
    """NerSAN vs. 阿爽 『Collapse』""",
    """totally ramified COC""",
    """TECHNOXMT vs. LATENCYPOLIS""",
    """XMT小咩兔 & Myna""",
    """IUIsauce""",
    """Likey & 百九十八""",
    """逆天使の悪魔 【Likey】""",
    """J.R""",
    """其二 向前迈进的理由""",
    """□MT in a XXXXXXXX""",
    """COC""",
    """急流に巻き込まれ""",
    """StupiGGy""",
    """COC  feat. Su1fuR""",
    """-JKy-""",
    """Barbarianerman & Regret""",
    """TimiTini →\"X\"← 阿爽""",
    """Simon_Axis•騎士•StR-1""",
    """完璧 × 北星""",
    """六回目Traveler Scend""",
    """RDRT -p 19:08:31""",
    """Ctymax respect for STAR TRACK in 2008""",
    """Barbarianerman feat. 晨""",
    """SimonAxis""",
    """M3d1uM & 百九十八""",
    """1uminous StaR""",
    """Likey feat. 198""",
    """StaR-1""",
    """OPENING/Level R""",
    """reanimate_6k_nm.imd""",
    """ネルサン (I make charts slowly)""",
    """Arenn Saki as \"lAβyrinS\"""",
    """無†極 fixed by Rikko""",
    """Pat Brick Man Mr.N feat. Ner of Time""",
    """Gausbon ~ See you next time ~ """,
    """白""",
    """百九十八 vs. Barbarianerman""",
    """-NerSAN & Su1fuR-""",
    """StR-1 & 右果_Ary""",
    """RipHall vs. Likey""",
    """头鱼头鱼 MAX Story!!""",
    """Gausbon fixed by XMT""",
    """Uvernight & Su1fuR""",
    """4B314C3042592B45""",
    """SantR""",
    """merry CNrisTimas""",
    """其三 我所存在的证明""",
    """阿爽 fixed by Clutter""",
    """信仰の剣『生』""",
    """Barbarianerman & NerSAN in the ICU""",
    """4D45474142592B45""",
    """-Seek A Lnside Truth-""",
    """Barbarianerman""",
    """Ner＜Jazz for your soul .)""",
    """不喜欢键的COC""",
    """扫佛不是嫂夫""",
    """Ctymax vs. 阿爽""",
    """NerSAN & 百九十八""",
    """平川の剣『士』""",
    """Alloces feat. Uvernight""",
    """Clutter vs. Salt""",
    """NerSANTA vs. BarbarianerSLEDGE""",
    """Raiky Season""",
    """WhiteCat.""",
    """奥術 ~The Empery~""",
    """Nr3_Official""",
    """while(TangScend==TangScend);""",
    """Su1fuR、快斬！""",
    """Gausbon & StupiGGy""",
    """StR-1""",
    """Barbarianerman & J.R""",
    """Believe Ctymax""",
    """Ctymax vs. 晨""",
    """Gausbounce""",
    """TimiTini""",
    """雑""",
    """HaraKuma""",
    """ST AS is XMT""",
    """RXhuang""",
    """Likey """,
    """R:kko (IMD)""",
    """A.S.H&晨""",
    """StR-9""",
    """NerSAN vs. 阿爽""",
    """Ctymax after 7 years""",
    """小咩兔的多指课堂 vs. 上课睡大觉""",
    """Salt & Barbarianerman""",
    """Яadiance""",
    """LDAJOY&PLEASANT ^V^ LDA""",
    """Max(C,t,y)""",
    """波之所杂""",
    """Simon_Axis vs. Su1fuR""",
    """Δ (M3d1uM vs. Salt)""",
    """Barbarianerman vs. Uvernight""",
    """Ctymax""",
    """Barbarianerman.exe""",
    """小咩兔、参上""",
    """断罪の剣『神』""",
    """{Destruction}""",
    """曦枢 vs. 鎏光 -Lv.70 LEAF-""",
    """完璧 [WARNING: DRAG OVERLOAD]""",
    """Hara小兔组""",
    """晨 vs. XMT小咩兔""",
    """フィグロス譜面チーム \"Rikko feat. Ner\" -Pray for \"PHI\"-""",
    """鲲&百九十八""",
    """Catcats & 百九十八 fixed by Clutter""",
    """Ctymax but 5 years later""",
    """奇跡の希""",
    """Burn Full Catcats""",
    """Gino""",
    """Executor-X""",
    """生根发芽的小咩兔""",
    """Ctymax vs. IUIsauce -村头烤鱼蘸凹酱-""",
    """St2.1GHz -Før The Pigeons-""",
    """Catcats & 百九十八""",
    """～漂泊者～凹酱""",
    """猫の信 & 百九十八""",
    """Sparkle Ctymax""",
    """BarbariaNerSAN feat. Snorkel""",
    """森德雷斯 vs. 百九十八""",
    """Ctymax drives in BlindForest""",
    """Barbarianerman, Overture before the story""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by 晨""",
    """Absolute(6)""",
    """Arenn Salty feat. LDA""",
    """Myna feat.Sleepyhead""",
    """unDefined Future""",
    """無極☆雷鳴 ~ ♫死の序曲♫""",
    """Deep Dark Ctymax""",
    """六回目Traveler Scend as \"Knight of Arq\"""",
    """XMT & 198""",
    """Gausbon vs. 阿爽""",
    """jeitie goes outside""",
    """J0(_)I2|\\|3y\'5 3|\\||)""",
    """Crush βETA""",
    """TangScend""",
    """FORGET :: CLUTTER""",
    """Ctymax vs. 百九十八""",
    """jouR.ney with hold""",
    """Latency, Finale of the dream""",
    """XMT & Salt""",
    """while(TangScend>=TangScend);""",
    """_鉄 (Isotope 59)""",
    """Ner as \"SPΔDE\"""",
    """Debut under spotlights!< Simon_Axis""",
    """NerSANN""",
    """Rikko""",
    """b.b.n.m.""",
    """Rikko EXPERT Lv.40""",
    """Snorkel vs. NerSAN""",
    """ANGER&SORROW >^< LDA""",
    """倪之所爽""",
    """Passport:Constructor""",
    """JKy""",
    """人外侵略地球计划""",
    """Likey affected by Ancestral Xhronicle""",
    """迟戈 vs. Likey""",
    """B.""",
    """NerSANTA & Gausbell""",
    """Manufacturer ~ Rikko""",
    """其一 呼吸尚存的标志""",
    """LonelyKnight""",
    """jeitie gets sent to the sun""",
    """LuminousGausbon""",
    """逆流而上的小咩兔""",
    """Barianic Baradise""",
    """_鉄""",
    """Salt & Uvernight""",
    """Brave Eaimo""",
    """Merry ChristymAxS""",
    """L.I.K.E.Y.""",
    """BLACK CTYMAX""",
    """Salt feat. XMT小咩兔""",
    """Creator ~ StupiGGy""",
    """SeveredEntity (BlindForest vs. rN) feat. Δ""",
    """CTYMAX ????""",
    """晨 vs. Ctymax""",
    """百九十八""",
    """Pat Brick Man Mr.C & Mr.B""",
    """ø""",
    """Passport:Governor""",
    """Barbarialid""",
    """RDRT -p 20:02:21""",
    """Believe Ctymax & TimiTini""",
    """爽夜讃歌""",
    """Clutter is coppery，Tumult is coppery""",
    """COLORFUL CTYMAX""",
    """Another M3""",
    """|R|I|K|K|O| NORMAL""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by 野从&晨""",
    """Rikko from「PHIGROS MOON」""",
    """Nothing But Likey""",
    """Clutter & Barbarianerman""",
    """Pat Brick Man Mr.C""",
    """晨 vs. 阿爽""",
    """XMT小咩兔 vs. Barbarianerman""",
    """時の希 & 百九十八""",
    """with U""",
    """NerSAN vs. Ctymax as \"泥头鱼\"""",
    """Alloces""",
    """while(TangScend=TangScend);""",
    """零號宇夜""",
    """-StupiGGy- fixed by 晨""",
    """A.S.H""",
    """Hook vs. _鉄""",
    """Demiurge ~ Dawn""",
    """ARE YOU JEITIE!!!""",
    """Clutter""",
    """上班睡大觉_Sleepyhead""",
    """Arenn Saki as \"mAze\"""",
    """野从菠萝""",
    """Bσrbσriσnermσn.exe""",
    """野从""",
    """Jαckψ feat. Βαρβαροςαντρας""",
    """鲲""",
    """Helabot""",
    """阿爽 eat Ctymax""",
    """Barbarvillea""",
    """クラッタ・アナザー・ラウンド""",
    """JKy vs StrayCat""",
    """Sillyp & Alloces""",
    """ParParianerman""",
    """s.t.p.g.""",
    """Snorkel""",
    """阿爽 & 百九十八""",
    """阿♪爽""",
    """C.Max (PBM)""",
    """阿爽 fixed by Barbarinerman""",
    """Another Stage""",
    """百九十八 feat. Likey""",
    """StuRmwind""",
    """Phigros Charting Team""",
    """Likey >IT\'S SHOWTIME!""",
    """NerSANNN""",
    """Likey""",
    """阿爽 vs. Ctymax -Haose 垃圾-""",
    """BlindForest 『Observing』""",
    """Ctymax vs. Gausbounce""",
    """Ctymax in a volcano, very delicious""",
    """Jαckψ""",
    """阿爽『Destroy』""",
    """IMD_6""",
    """弧光 With Opposition""",
    """R.""",
    """騎士 vs. Knight """,
    """HD R.esolution""",
    """Pcat【零】198""",
    """Bear""",
    """Gausbon feat. 迟戈&野从""",
    """無彩色""",
    """thrAsh forSe""",
    """Eaimo fixed by NerSAN""",
    """XMT is silvery, 小咩兔 is silvery""",
    """壹號阿爽""",
    """4731474142592B45""",
    """Apocalyptic Dissonance""",
    """JKy, the inferior""",
    """夜明の剣『靈』""",
    """StR-1 watches Ctyfilm""",
    """Lumiere""",
    """merry XM AS""",
    """Knight""",
    """さるふるふるさ""",
    """Likey & 198ar""",
    """Ner, the inferior""",
    """Barbarianerman vs. Alloces""",
    """vesper/straycat""",
    """『流』年大顺""",
    """ɹǝʇʇnlƆ""",
    """We are the Miserable""",
    """Doubt Ful""",
    """空の希""",
    """百九十八 busting 阿爽""",
    """Passport:Visitor""",
    """imd visual charter \"Rikko\" since 2014""",
    """Barbarianerman fixed by Clutter""",
    """Blessing beyond myself.""",
    """StupiGGy -The Origin-""",
    """Su1fuR -FAISEURS DE PANIQUE-""",
    """実戦 with Rikko""",
    """縱連打の信者☆無極""",
    """Bariantum Hyperianerman""",
    """椒盐倪尔""",
    """Ctymax vs. 阿爽  fixed by B B M pow""",
    """COLORFUL BLACK GAUSBON""",
    """完璧 vs 癒株 -Autumn Memory-""",
    """Jeitie""",
    """dancing\"L\"ine 2085""",
    """Ctymax vs. Barbarianerman""",
    """撕裂者『無極』 fixed by 晨""",
    """Believe TimiTini""",
    """Pcat & 百九十八""",
    """杂波不是杂啵，野从不是野丛""",
    """&ikko""",
    """上班摸大鱼 a.k.a. 海洋咩兔""",
    """Hara is golden, Kuma is golden""",
    """対流に巻き込まれ""",
    """iv""",
    """SPΔDE & 倪尔qwq""",
    """Jαckψ a.k.a JKy""",
    """村头村头 CTY Story!!""",
    """[!!12:l<l<ο!!]""",
    """Sillyp vs. 晨""",
    """Sempiternal Fxxxxxx Resolution!""",
    """晨""",
    """Divination Fortune""",
    """分化者 fixed by Barbarianerman""",
    """Clutter BETA""",
    """Simon_Axis vs. Likey [Respect Ner as \"SP∆DE\"]""",
    """Likey & Barbarianerman""",
    """THE LAST 198""",
    """Ner ~Freaky Cat of Charting~""",
    """Rikko³ [Normal]""",
    """Simon_Axis >< Likey""",
    """NerSAN""",
    """Warning: XMT is infected by Trojan!!""",
    """198 in Kowloon""",
    """KillJoy""",
    """-""",
    """奇跡の希 feat. 奇跡の従""",
    """Rikko & TangScend""",
    """不喜欢线的COC""",
    """『兔』年大吉""",
    """Clutter Echo""",
    """Drop Catcats""",
    """XMT wishing upon a satellite""",
    """CorruptedEntity & 野从""",
    """Find_Ctymax""",
    """Gausbon""",
    """Barbarianerman vs. NerSAN""",
    """N\\erry Xmas 2024""",
    """\'\'-1\'\'""",
    """<= Noblesse Jeitie =>""",
    """Bσrbσriσn∑rmσn.∑x∑""",
    """鲲 fixed by 百九十八""",
    """Salt feat. M3ow""",
    """Concat(Ramification,Richter)""",
    """阿爽""",
    """Uvernight""",
    """StrayCat""",
    """Sillyp vs. 阿爽""",
    """Xlutter guided by three Oaths""",
    """孤独な騎士 Against 魔王、大咩兔""",
    """Barbarianerman feat. Gausbon""",
    """Another cat""",
    """XMT小咩兔 vs. 上班睡大觉_Sleepyhead""",
    """Barbarianerman vs. HaraKuma""",
    """Gausbounce & 晨""",
    """monochrome ILLUSION""",
    """N\\erry Xmas""",
    """晨_鉄""",
    """阿爽 fixed by Barbarianerman""",
]

# 组合名称;
COMBINE_NAME: list[str] = [
    """Glaciaxion.SunsetRay""",
    """EradicationCatastrophe.NceS""",
    """Credits.Frums""",
    """Dlyrotz.Likey""",
    """EnginexStartmelodymix.CrossingSound""",
    """光.姜米條""",
    """Wintercube.CtymaxfeatNceS""",
    """Cipher20.TetrajectoryfeatCtymax""",
    """混乱Confusion.OnlyMyBlackScore""",
    """FULiAUTOSHOOTER.MYUKKE""",
    """HumaN.SOTUI""",
    """PRAW.Bluewind""",
    """PixelRebelz.Normal1zer""",
    """Cereris.SunsetRayNceS""",
    """NonMelodicRagezMUGEdit.Normal1zer""",
    """SultanRage.MonstDeath""",
    """ClassMemories.AntistarfeatCtymax""",
    """SURREALISM.Itsuki""",
    """BonusTime.MegaloPaleWhite""",
    """ENERGYSYNERGYMATRIX.Tanchiky""",
    """NYA.FLuoRiTe姜米條""",
    """JunXionBetweenLifeAndDeathVIPMix.1N6Fs""",
    """cryout.JuE""",
    """Reimei.影虎""",
    """尊師TheGuru.rider""",
    """Spasmodic.姜米條颶風元力上人""",
    """LeaveAllBehind.rider""",
    """ColorfulDays.P4koofeatつゆり花鈴""",
    """microwav.dandeless""",
    """重生.姜米條""",
    """NOONEYESMAN.MYUKKE""",
    """望影の方舟Six.SeURa""",
    """Igallta.SeURa""",
    """ClockParadox.WyvernP""",
    """Chronologika.Hundotte""",
    """NickofTime.P4koo""",
    """Chronomia.Lime""",
    """ChronosCollapseLaCampanella.SunsetRay""",
    """Rrharil.TeamGrimoire""",
    """CraveWave.LandRoot""",
    """TheChariotREVIIVAL.Attoclef""",
    """Luminescence.米虾Fomiki初云CLoudie""",
    """Retribution.nmyKryexe""",
    """DESTRUCTION321.Normal1zervsBrokenNerdz""",
    """DistortedFate.Sakuzyo""",
    """Doppelganger.LeaF""",
    """もぺもぺ.LeaF""",
    """MARENOL.LeaF""",
    """萤火虫の怨.闫东炜""",
    """万吨匿名信.闫东炜""",
    """风屿.闫东炜""",
    """dBdoll.YUESTEVENuen""",
    """Dash.小红Akane李祥辉""",
    """云女孩.符白牙SiYFics""",
    """DropIt.Asuka""",
    """RIPPER.Friedwav""",
    """Aphasia.闫东炜""",
    """开心病.闫东炜""",
    """華灯爱.闫东炜""",
    """FindMe.Kforest""",
    """Sein.朔Apo11oprogramvsお月さま交響曲ftkuroa荒巻""",
    """狂喜蘭舞.LeaF""",
    """SparkleNewLife.rider""",
    """KhronostasisKatharsis.Halv""",
    """SnowDesert.WyvernP""",
    """Burn.NceS""",
    """Aleph0.LeaF""",
    """NextTime.SaMZIng""",
    """RubbishSorting.CtymaxvsNceS""",
    """AnotherMe.NeutralMoon""",
    """mechanted.rareguy""",
    """lifeflashesbeforeweebeyes.BilliumMoto""",
    """BreakThroughTheBarrier.lixound""",
    """Chronostasis.黒皇帝""",
    """DeadSoul.SoundSouler""",
    """InfinityHeaven.HyuN""",
    """Disorder.HyuNfeatYURI""",
    """CROSSSOUL.HyuNfeatSyepias""",
    """SpeedUp.DarTokki""",
    """MagentaPotion.EmoCo""",
    """GetBack.CAP3""",
    """Palescreen.WyvernPfeatMadol""",
    """GOODTEK.EBIMAYO""",
    """GOODBOUNCE.EBIMAYO""",
    """GOODWORLD.EBIMAYO""",
    """GOODFORTUNE.EBIMAYO""",
    """GOODRAGE.EBIMAYO""",
    """TheMountainEater.PaulBazooka""",
    """Orthodox.tokiwa""",
    """EndMe.ZxNXasDelaina""",
    """ParallelRetrogressionGameVer.Tetrajectory""",
    """Starduster.Quree""",
    """Electron.ElousFZ""",
    """SIGMA.Kryexe""",
    """HardcoreKwaya.EnFr""",
    """Aventyr.GrandThawRigelTheatre""",
    """Trane.MALVA""",
    """雪降りメリクリ.A39""",
    """CervelleConnexion.SCTL""",
    """modulus.PTB10""",
    """Wavetapper.Frums""",
    """大和撫子WildDances.adapatorvsDRIVE""",
    """Eltaw.Fl00t""",
    """Initialize.iF""",
    """桜樹街道.kozatosnow""",
    """GetReady.iF""",
    """volcanic.DETROakaルゼ""",
    """BetterGraphicAnimation.ルゼ""",
    """XING.ginkiha""",
    """FinalStep.Lime""",
    """Cthugha.USAO""",
    """WithYou.Cashew""",
    """UnorthodoxThoughts.Joulez""",
    """Apocalyptic.ZClaxxSumaiLight""",
    """游园地.椒盐菠萝""",
    """energytrixxx.KAH""",
    """Nhelv.Silentroom""",
    """Arkhei.SeraAmagi""",
    """Kerberos.Zris""",
    """parsey.siqlo""",
    """Concvssion.Halv""",
    """ジングルベルJingleBell.A39沙包P""",
    """TimetoNightSkyfeatLeeYuJin.HyuNKLYDIX""",
    """HAZARD.Limpid""",
    """AnotherMe.DAAN""",
    """DontNeverAround.HAMA""",
    """RESSiSTANCE.ぐるたみん""",
    """Dreamland.z1onkyrrin""",
    """AnotherRound.JustinDai""",
    """996.李化禹""",
    """FutureMind.RayNauticaRekuMochizuki""",
    """Luminescent.Daison""",
    """FULiAUTOBUSTER.MYUKKE""",
    """IMustSayNo.TangJuan""",
    """opia.rN""",
    """Apocalypse.アリスシャッハと魔法の楽団""",
    """Protoflicker.Silentroom""",
    """HorizonBlue.NothingButRequiemfeatAikapinChiyoko""",
    """YouaretheMiserable.tpazolite""",
    """Stasis.Maozon""",
    """いざ参ります.Uskefeat棗いつき""",
    """月下缭乱.月見静華vsLUNARiUM""",
    """OnAndOn.ETIAfeatJenga""",
    """DataErr0r.Cosmograph""",
    """Shadow.SumaiLightvs姜米條""",
    """心之所向.姜米條""",
    """inferior.姜米條""",
    """csqn.Aoi""",
    """BraveNotes.TurquoiseDRIVENota""",
    """盏茗.茶鸣拾贰律""",
    """青芽.茶鸣拾贰律""",
    """EternalSnow.AbyssIdols""",
    """RainySeason.AbyssIdols""",
    """ElCondorPasaPhigrosEdit.PlasticFruits""",
    """BreakOver.Kforest""",
    """BelieveLightfeat果丸哒呦.ScalerMestie果丸哒呦""",
    """Pontdessouvenirs.VeetaCrushvsitsufeatitsu""",
    """青丘.BLACK0""",
    """瓷岁.茶鸣拾贰律""",
    """Feast远东之宴.茶鸣拾贰律""",
    """インフェルノシティ.Ponchifeatはぁち""",
    """Upshift.Iriss-Frantzz""",
    """PoisonANDORAffection.LeaF""",
    """Random.SobremSilentroom""",
    """零號車輛.seatrus""",
    """NowIsTheTimeDoIt.RoyMikelate""",
    """Bougainvillea.Jade""",
    """神話.PicaM2U""",
    """Elúltimobaile.Θ""",
    """Trojan.litmus""",
    """TemporalShifting.LureRabbitVC""",
    """Adastraperaspera.RabbitHouse""",
    """Ajourneytothemoonlight.Yesod""",
    """RainyHeart.BelieverInYou阿卡姆巫师""",
    """Realms.HinkikAHimitsu""",
    """ぱぴぷぴぷぴぱ.ころねぽちWith立秋""",
    """TriumphRegret.typeMARS""",
    """SATELLITE.かめりあ""",
    """DancewithSilence.かめりあ""",
    """LabyrinthinKowloonWalledWorld.かめりあ""",
    """ComputeItWithSomeDevilishAlcoholicSteampunkEngines.かめりあ""",
    """ERABYECONNEC10N.かめりあ""",
    """DiamondEyes.SYNTHETIC""",
    """Bitterblossom.imvi""",
    """SilenceisGoldenSpeechisGolden.NIWASHI""",
    """FracturedAngel.DJRaisei""",
    """JourneywithYou.Iris""",
    """SecretIllumination.Yooh""",
    """InvertedWorld.ARForest""",
    """月詠に鳴る.Feryquitousfeat藍月なくる""",
    """TECHNOPOLIS2085.PRASTIKDANCEFLOOR""",
    """祈-我ら神祖と共に歩む者なり-.光吉猛修VS穴山大輔VSKaiVS水野健治VS大国奏音""",
    """bye.DingerBox""",
    """聖夜讃歌.A39沙包P""",
    """ストレイソウルアラウンド.みーに""",
    """ManifoldHypothesis.cybermisofeattigerlily""",
    """KMoeVIP.ZxNX""",
    """GVNGlitterVomitusandNeon.SaltySaltUnfold33""",
    """CrushBETA.shadow_bling""",
    """BrokenSky.JungoMAX3feat刘佳宜Snow幻影刃shadow""",
    """BRAINHACKER.SOMON""",
    """Xenolith.Tatsh""",
    """ArtificialExistence.JunKuroda""",
    """IndelibleScar.Noah""",
    """Antithese.Blacklolita""",
    """PRAGMATISMRESURRECTION.Laur""",
    """ShineAfter.ADeanJocularACE""",
    """Bloom.targ麻团qwq""",
    """幽世桔梗.Capchiifeatまるもこ""",
    """千紫万紅.r0yvsWABI""",
    """明鏡烈火.MUEvsRekuMochizuki""",
    """今天不是明天.PIKASONICfeat兰音Reine""",
    """Cuvism.Fl00tvsHalv""",
    """iLArtifact.Link0""",
    """atruthseekerCommunicationwithUtopiawillbelost.kuro""",
    """BoundedQuietude.FiniteLimitvsSiLiS""",
    """君往何处QuoVadis.M2U""",
    """暗夜苏醒REANIMATE.Warak""",
    """Grimheart.Puru""",
    """Thrashforce.KAHvsE0ri4""",
    """Originally.SNKSMizku""",
    """黄金之城GOLDTOWN.Memme""",
    """双重间谍DoubleAgent.WAVAV""",
    """幻影鬼魅PLEASE.R300K""",
    """Schadenfreude.ZxNX""",
    """Letempsperdu.Daison""",
    """FixationsTowardtheStars.Foodbot""",
    """valorstarcross.LundyvsWyvren""",
    """CometFeat符白牙.CNHKSS""",
    """白と黒のバケモノ.テヅカ""",
    """Devotion.Connexio""",
    """KirakiraNoelStory.RekuMochizuki""",
    """Shelter.MeatyRabbitNceS""",
    """蝎虎天体Lacertid.CreamvsDaily天利""",
    """贝多芬祝福BeethovenBlessing.Nauts""",
    """インマイマインド.レシオP""",
    """ニライカナイNiraicA_naiMix.roopfromSTR""",
    """SwingSkipDrop.ミハイル""",
    """宇宙残骸少女CosmicDustyGirl.辻原一郎""",
    """Resolver.Gomadare""",
    """LuminousEntitiesLostHeart.NormalMfeatUsagiDenki""",
    """KIZUNAResolution.TAG""",
    """AbsoluTedisoRdeR.AcuteDisarray""",
    """AphroditesChildshortver.RUQOA""",
    """DevIAtiOnshortver.polysha""",
    """NOx.Juggernaut""",
    """Aliceinaxxxxxxxx.Nagiha""",
    """Radiance.Nhato""",
    """DiamondDust.MasahiroGodspeedAoki""",
    """StardustRAY.kanonevsBlackY""",
    """FrozenHeart.A39沙包P""",
    """Helios.NOABotaNya""",
    """FlutterEcho.Cansol""",
    """Rebirth.ああああ""",
    """AvataarReincarnationofKalpa.ScarletteakaCrYmson""",
    """雪降り雪が降っている.AiSSw夜輪ft結月ゆかり""",
    """RetributionCycleofRedemption.ArdolfvsDaily天利""",
    """アンビバレンス.すりぃ相沢""",
    """Komplexe.雄之助featSennzai""",
    """slips.rintarosoma""",
    """QZKagoRequiem.tpazolite""",
    """Poseidon.1112vsStar""",
    """WATER.A39沙包P""",
    """MiracleForestVIPMix.Rinthlive""",
    """MOBILYS.Dachs""",
    """Lyrith迷宮リリス.ユメミド""",
    """Demiurge.Rabpit""",
    """Demonkin.ForgedReigns""",
    """Re_NascencePsystyleVer.Rinth_live""",
    """Ark.kanoryo""",
    """AfterDawn.S9ryne""",
    """INFiNiTEENERZYOverdoze.RekuMochizuki""",
    """Khalid.Dolphin""",
    """QuantumHyperspace.D_AAN""",
    """FreakyUndulationsNobleKnightsofTune.JehezukielKURORAK""",
    """PANICPARADISE.DJSHIONY""",
    """ReEndofaDream.umavsモリモリあつし""",
    """心の記憶.A39沙包P""",
    """Spotlight.Ardolf""",
    """NightTheater.わかどり""",
    """Ramification.rareguyReina""",
    """DerRichter.Ωμεγα""",
    """ATHAZA.LeaF""",
]


# 获取评级
def get_score_level(score: int, is_fc: bool = False) -> score_level_type:
    if score == 1000000:
        return score_level_type.phi
    elif is_fc:
        return score_level_type.VFC
    elif score >= 960000:
        return score_level_type.V
    elif score >= 920000:
        return score_level_type.S
    elif score >= 880000:
        return score_level_type.A
    elif score >= 820000:
        return score_level_type.B
    elif score >= 600000:
        return score_level_type.C
    else:
        return score_level_type.F
