from enum import Enum
import pandas as pd


# ------------------------- 这里写自定义的枚举量 -------------------------
class score_level_type(Enum):
    F = "F"
    C = "C"
    B = "B"
    A = "A"
    S = "S"
    V = "V"
    VFC = "蓝V"
    phi = "phi"


class special_type(Enum):
    AP = "AP"
    FC = "FC"
    NO_PLAY = "NO_PLAY"  # 还没玩过
    EMPTY = ""  # 无特殊状态


# 默认路径
# 整个文件的相对路径前缀
FILE_PATH = "python/rhythmgame_database/"
# 主文件夹下的文件可以直接写
CODE_PATH = FILE_PATH + "main_code.py"

# 固定的运行依赖文件夹
DEPENDENCES_PREPATH = FILE_PATH + "dependences/"

DIFFICULTY_PATH = DEPENDENCES_PREPATH + "difficulty.tsv"  # 各个歌曲难度文件
INFO_PATH = DEPENDENCES_PREPATH + "info.tsv"  # 组合名称与拆分名称对应关系文件
AVATAR_PATH = DEPENDENCES_PREPATH + "avatar.txt"  # 头像名称

# 字体文件
FONT_PREPATH = DEPENDENCES_PREPATH + "font/"

EN_FONT1 = FONT_PREPATH + "Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf"
NUM_FONT1 = FONT_PREPATH + "Share_Tech_Mono/ShareTechMono-Regular.ttf"
CHI_FONT1 = FONT_PREPATH + "ZCOOLKuaiLe/ZCOOLKuaiLe-Regular.ttf"

# 玩家信息(player_info)文件夹下文件的路径前缀
PLAYER_INFO_PREPATH = FILE_PATH + "player_info/"

TOKEN_PATH = PLAYER_INFO_PREPATH + "session_token.txt"  # 玩家session_token存储路径
GROUP_PATH = PLAYER_INFO_PREPATH + "group.csv"  # 玩家自定义分组信息存储路径
COMMENT_PATH = PLAYER_INFO_PREPATH + "comment.csv"  # 玩家自定义简评信息存储路径
TAG_PATH = PLAYER_INFO_PREPATH + "tag.csv"  # 玩家自定义标签信息存储路径

# 图片素材(images)文件夹下文件的路径前缀
IMAGES_PREPATH = FILE_PATH + "images/"

# 头像图片路径前缀
AVATER_IMG_PREPATH = IMAGES_PREPATH + "avatar/"

# 各种小图标
ICON_PREPATH = IMAGES_PREPATH + "icons/"

RESET_PATH = ICON_PREPATH + "reset.png"
SAVE_ICON_PATH = ICON_PREPATH + "save.png"
GENERATE_RKS_ICON_PATH = ICON_PREPATH + "generate_rks_compose.png"
FILTER_ICON_PATH = ICON_PREPATH + "filter.png"
FILTER_AGAIN_ICON_PATH = ICON_PREPATH + "filter_again.png"

SCORE_LEVEL_ICONS_PREPATH = ICON_PREPATH + "score_level_icons/"

SCORE_LEVEL_PATH = {
    score_level_type.F: SCORE_LEVEL_ICONS_PREPATH + "F.png",
    score_level_type.C: SCORE_LEVEL_ICONS_PREPATH + "C.png",
    score_level_type.B: SCORE_LEVEL_ICONS_PREPATH + "B.png",
    score_level_type.A: SCORE_LEVEL_ICONS_PREPATH + "A.png",
    score_level_type.S: SCORE_LEVEL_ICONS_PREPATH + "S.png",
    score_level_type.V: SCORE_LEVEL_ICONS_PREPATH + "V.png",
    score_level_type.VFC: SCORE_LEVEL_ICONS_PREPATH + "VFC.png",
    score_level_type.phi: SCORE_LEVEL_ICONS_PREPATH + "phi.png",
}

# 生成的二维码与空二维码
QRCODE_IMG_PREPATH = IMAGES_PREPATH + "QRcode/"

QRCODE_IMG_PATH = QRCODE_IMG_PREPATH + "QRcode.png"
QRCODE_EMPTY_IMG_PATH = QRCODE_IMG_PREPATH + "QRcode_empty.jpg"

# 各种背景
BACKGROUND_IMG_PREPATH = IMAGES_PREPATH + "background/"

SONG_CARD_BACKGROUND = {  # 区分不同难度的背景
    "EZ": BACKGROUND_IMG_PREPATH + "green-EZ.png",
    "HD": BACKGROUND_IMG_PREPATH + "blue-HD.png",
    "IN": BACKGROUND_IMG_PREPATH + "red-IN.png",
    "AT": BACKGROUND_IMG_PREPATH + "gold-AT.png",
}

# 曲绘
ILLUSTRATION_PREPATH = IMAGES_PREPATH + "illustration/"


# 默认样式表
def get_combobox_style(
    font_size: str = 23,
    max_width: str = 360,
    min_width: str = 360,
    min_height: str = 50,
    max_height: str = 50,
    border_radius: str = 7,
    background_color: tuple[str, str, str, str] = (255, 255, 255, 0),
):
    style = "ComboBox {\n"
    r, g, b, a = background_color
    style += f"""
    font-size: {font_size}px;
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    border: 2px solid black;
    border-radius: {border_radius}px;
    background-color: rgba({r},{g},{b},{a});
    text-align: left;
    padding-left: 5px;
    """
    style += "}"
    return style


def get_button_style(
    max_width: str = 360,
    min_width: str = 360,
    min_height: str = 50,
    max_height: str = 50,
    font_family: str = "仿宋",
    font_size: str = 34,
    border_radius: str = 7,
    background_color: tuple[str, str, str, str] = (0, 159, 170, 1),
    color: str = "white",
):
    style = "PushButton {\n "
    r, g, b, a = background_color
    contain = f"""
    font-size: {font_size}px;
    font-family: "{font_family}";
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    border-radius: {border_radius}px;
    background-color: rgba({r},{g},{b},{a});
    color: {color};
    """
    style += (
        contain
        + """
        }
    PushButton:hover {
        background-color: #00CDCD;
    }
    PushButton:pressed {
        background-color: #00FFFF;
    }"""
    )
    return style


def get_label_style(
    font_size: str = 26,
    max_width: str = 80,
    min_width: str = 80,
    min_height: str = 50,
    max_height: str = 50,
    font_family: str = "楷体",
    font_color: tuple[int, int, int, int] = (0, 0, 0, 1),
    background_color: tuple[int, int, int, int] = (255, 255, 255, 0),
):
    style = """QLabel {\n"""
    r, g, b, a = background_color
    fr, fg, fb, fa = font_color
    style += f"""
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    font-size: {font_size}px;
    font-family: '{font_family}';
    color: rgba({fr},{fg},{fb},{fa});
    background-color: rgba({r},{g},{b},{a});
    """
    style += "}"
    return style


def get_input_box_style(
    max_width: str = 300,
    min_width: str = 300,
    min_height: str = 60,
    max_height: str = 60,
    font_family: str = "仿宋",
    font_size: str = 28,
    border_radius: str = 7,
    background_color: tuple[str, str, str, str] = (255, 248, 220, 1),
):
    style = "LineEdit {\n "
    r, g, b, a = background_color
    style += f"""
    font-size: {font_size}px;
    font-family: "{font_family}";
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    border-radius: {border_radius}px;
    background-color: rgba({r},{g},{b},{a});
    """
    style += "}"
    return style


def get_switch_button_style(
    max_width: str = 250,
    min_width: str = 250,
    min_height: str = 30,
    max_height: str = 30,
):
    style = "SwitchButton {\n"
    style += f"""
    max-width: {max_width}px;
    min-width: {min_width}px;
    min-height: {min_height}px;
    max-height: {max_height}px;
    """
    style += "}"
    return style


DEFAULT_EN_FONT = "Segoe UI"
DEFAULT_CN_FONT = "Microsoft YaHei"
DEFAULT_JP_FONT = "Yu Gothic UI"


FILTER_ATTRIBUTION_LIST: list[str] = [
    "acc",
    "单曲rks",
    "得分",
    "定数",
    "评级",
    "难度",
    "曲名",
    "曲师",
    "谱师",
    "画师",
    "分组",
    "标签",
    "简评",
]

# 数值类比较
NUMERIC_COMPARATORS: list[str] = [
    "大于",
    "大于等于",
    "小于",
    "小于等于",
    "等于",
    "不等于",
]

# 精确 模糊比较
LOGICAL_OPERATORS: list[str] = ["等于", "不等于", "包含", "不包含"]

# 曲名
SONG_NAME_LIST: list[str] = [
    "Glaciaxion",
    "Eradication Catastrophe",
    "Credits",
    "Dlyrotz",
    "Engine x Start!! (melody mix)",
    "光",
    "Winter ↑cube↓",
    "Cipher : /2&//<|0",
    "混乱-Confusion",
    "FULi AUTO SHOOTER",
    "HumaN",
    "[PRAW]",
    "Pixel Rebelz",
    "Cereris",
    "Non-Melodic Ragez (MUG Edit)",
    "Sultan Rage",
    "Class Memories",
    "-SURREALISM-",
    "Bonus Time",
    "ENERGY SYNERGY MATRIX",
    "NYA!!! (Phigros ver.)",
    "JunXion Between Life And Death(VIP Mix)",
    "cryout",
    "Reimei",
    "尊師 ～The Guru～",
    "Spasmodic",
    "Leave All Behind",
    "Colorful Days♪",
    "micro.wav",
    "重生",
    "NO ONE YES MAN",
    "望影の方舟Six",
    "Igallta",
    "Clock Paradox",
    "Chronologika",
    "Nick of Time",
    "Chronomia",
    "Chronos Collapse - La Campanella",
    "Rrhar'il",
    "Crave Wave",
    "The Chariot ~REVIIVAL~",
    "Luminescence",
    "Retribution",
    "DESTRUCTION 3,2,1",
    "Distorted Fate",
    "Doppelganger",
    "もぺもぺ",
    "MARENOL",
    "萤火虫の怨",
    "万吨匿名信",
    "风屿",
    "dB doll",
    "Dash",
    "云女孩",
    "Drop It",
    "RIPPER",
    "Aphasia",
    "开心病",
    "華灯爱",
    "Find_Me",
    "Sein",
    "狂喜蘭舞",
    "Sparkle New Life",
    "Khronostasis Katharsis",
    "Snow Desert",
    "Burn",
    "Aleph-0",
    "Next Time",
    "Rubbish Sorting",
    "Another Me",
    "mechanted",
    "life flashes before weeb eyes",
    "Break Through The Barrier",
    "Chronostasis",
    "Dead Soul",
    "Infinity Heaven",
    "Disorder",
    "CROSS†SOUL",
    "Speed Up!",
    "Magenta Potion",
    "Get Back",
    "Palescreen",
    "GOODTEK",
    "GOODBOUNCE",
    "GOODWORLD",
    "GOODFORTUNE",
    "GOODRAGE",
    "The Mountain Eater",
    "Orthodox",
    "End Me",
    "Parallel Retrogression(Game Ver.)",
    "Starduster",
    "Electron",
    "SIGMA",
    "Hardcore Kwaya",
    "Äventyr",
    "Träne",
    "雪降り、メリクリ",
    "Cervelle Connexion",
    "modulus",
    "Wavetapper",
    "大和撫子 -Wild Dances-",
    "Eltaw",
    "Initialize",
    "桜樹街道",
    "Get Ready!! ",
    "volcanic",
    "Better Graphic Animation",
    "XING",
    "Final Step!",
    "Cthugha",
    "With You",
    "Unorthodox Thoughts",
    "Apocalyptic",
    "游园地",
    "energy trixxx",
    "Nhelv",
    "-Arkhei-",
    "Kerberos",
    "ρars/ey",
    "Concvssion",
    "ジングルベル(Jingle Bell)",
    "Time to Night Sky (feat. Lee Yu Jin)",
    "HAZARD",
    "Another Me",
    "Don't Never Around",
    "RESSiSTANCE",
    "Dreamland",
    "Another Round",
    "996",
    "Future Mind",
    "Luminescent",
    "FULi AUTO BUSTER",
    "I Must Say No",
    "opia",
    "Apocalypse",
    "Protoflicker",
    "Horizon Blue",
    "You are the Miserable",
    "Stasis",
    "いざ、参ります",
    "月下缭乱",
    "On And On!!",
    "DataErr0r",
    "Shadow",
    "心之所向",
    "inferior",
    "c.s.q.n.",
    "Brave Notes",
    "盏茗",
    "青芽",
    "Eternal Snow",
    "Rainy Season",
    "El Condor Pasa (Phigros Edit)",
    "Break Over",
    "Believe Light (feat. 果丸哒呦)",
    "Pont des souvenirs",
    "青丘",
    "瓷岁",
    "Feast远东之宴",
    "インフェルノシティ",
    "Upshift",
    "Poison AND÷OR Affection",
    "Random",
    "零號車輛",
    "Now Is The Time, Do It",
    "Bougainvillea",
    "神話",
    "El último baile",
    "Trojan",
    "Temporal Shifting",
    "Ad astra per aspera",
    "A journey to the moonlight",
    "Rainy Heart",
    "Realms",
    "ぱぴぷぴぷぴぱ",
    "Triumph & Regret",
    "S.A.T.E.L.L.I.T.E.",
    "Dance with Silence",
    "Labyrinth in Kowloon: Walled World",
    "Compute It With Some Devilish Alcoholic Steampunk Engines",
    "+ERABY+E CONNEC+10N",
    "Diamond Eyes",
    "Bitterblossom",
    "Silence is Golden, Speech is Golden",
    "Fractured Angel",
    "Journey with You",
    "Secret Illumination",
    "Inverted World",
    "月詠に鳴る",
    "TECHNOPOLIS 2085",
    "祈 -我ら神祖と共に歩む者なり-",
    "bye",
    "聖夜讃歌",
    "ストレイソウル・アラウンド",
    "Manifold Hypothesis",
    "K.Moe (VIP)",
    "G.V.N. (Glitter,Vomitus and Neon)",
    "Crush BETA",
    "Broken Sky",
    "BRAIN HACKER",
    "Xenolith",
    "Artificial Existence",
    "Indelible Scar",
    "Antithese",
    "PRAGMATISM -RESURRECTION-",
    "Shine After",
    "Bloom",
    "幽世桔梗",
    "千紫万紅",
    "明鏡烈火",
    "今天不是明天",
    "Cuvism³",
    "iL-Artifact",
    "a truth seeker -Communication with Utopia will be lost-",
    "Bounded Quietude",
    "君往何处 (Quo Vadis)",
    "暗夜苏醒 (REANIMATE)",
    "Grimheart",
    "Thrash force",
    "Originally",
    "黄金之城 (GOLD TOWN)",
    "双重间谍 (Double Agent)",
    "幻影鬼魅 (PLEASE)",
    "Schadenfreude",
    "Le temps perdu",
    "Fixations Toward the Stars",
    "valor/starcross",
    "Comet",
    "白と黒のバケモノ",
    "Devotion",
    "Kirakira Noel Story!!",
    "Shelter",
    "蝎虎天体 -Lacertid-",
    "贝多芬祝福 (Beethoven Blessing)",
    "インマイマインド",
    "ニライカナイ (NiraicA_nai Mix)",
    "Swing Skip Drop",
    "宇宙残骸少女 (Cosmic Dusty Girl)",
    "Resolver",
    "Luminous Entities Lost Heart",
    "KIZUNA Resolution",
    "AbsoluTe disoRdeR",
    "Aphrodite's Child (short ver.)",
    "DevIAtiOn (short ver.)",
    "NO x",
    "Alice in a xxxxxxxx",
    "Radiance",
    "Diamond Dust",
    "Stardust:RAY",
    "Frozen Heart",
    "Helios",
    "Flutter Echo",
    "Re：birth",
    "Avataar~Reincarnation of Kalpa~",
    "Ποσειδών",
    "WATER",
    "Miracle Forest (VIP Mix)",
    "MOBILYS",
    "Lyrith -迷宮リリス-",
    "Demiurge",
    "Demonkin",
    "Re_Nascence (Psystyle Ver.) ",
    "Ark",
    "After Dawn",
    "INFiNiTE ENERZY -Overdoze-",
    "Khalid",
    "Quantum Hyperspace",
    "Freaky Undulations ~Noble Knights of Tune~",
    "PANIC PARADISE",
    "Re：End of a Dream",
    "心の記憶",
    "Spotlight",
    "NightTheater",
    "Ramification",
    "Der Richter",
    "ATHAZA",
]


# 曲师
COMPOSER_LIST: list[str] = [
    "ああああ",
    "r0y vs. WABI",
    "Puru",
    "Scarlette a.k.a CrYmson",
    "ユメミド",
    "Rinth_live",
    "Likey",
    "ぐるたみん",
    "影虎。",
    "Megalo_PaleWhite",
    "iF",
    "Z ClaxX & SumaiLight",
    "z1on & kyrrin",
    "米虾Fomiki & 初云CLoudie",
    "Attoclef",
    "姜米條&SumaiLight",
    "Θ",
    "Ctymax vs. NceS",
    "Zris",
    "A-39/沙包P",
    "Ju_E",
    "VeetaCrush vs. [itsu(feat.itsu)]",
    "Pica & M2U",
    "Scaler & Mestie & 果丸哒呦",
    "光吉猛修 VS 穴山大輔 VS Kai VS 水野健治 VS 大国奏音",
    "Roy Mikelate",
    "HyuN & KLYDIX",
    "M-UE vs. Reku Mochizuki",
    "Nhato",
    "imvi",
    "Tanchiky",
    "tokiwa",
    "Plastic Fruits",
    "Iriss-Frantzz",
    "Frums",
    "Lure Rabbit & V!C",
    "polysha",
    "DingerBox",
    "黒皇帝",
    "Salty Salt & Unfold33",
    "椒盐菠萝",
    "Noah",
    "A-39 / 沙包P",
    "Silentroom",
    "rareguy & Reina",
    "辻原一郎",
    "Fl00t",
    "WyvernP",
    'ZxNX as "Delaina"',
    "NOA(Cortrix) & BotaNya",
    "ミハイル",
    "Jade",
    "Capchii feat. まるもこ",
    "Yesod",
    "Friedwav",
    "lixound",
    "NIWASHI",
    "ElousΛ.-FZ",
    "Quree",
    "Bluewind",
    "符白牙/SiYFics",
    "BilliumMoto",
    "Jehezukiel + KURORAK",
    "NceS",
    "Neutral Moon",
    "Laur",
    "Team Grimoire",
    "LandRoot",
    "rN",
    "Daison",
    "Link''0",
    "DarTokki",
    "SYNTHETIC",
    "Fl00t vs Halv",
    "Rabbit House",
    "Sera Amagi",
    "EmoCo.",
    "Feryquitous feat.藍月なくる",
    "HyuN feat. YURI",
    "Foodbot",
    "テヅカ",
    "A-39",
    "Hundotte",
    "USAO",
    "BLACK 0",
    "Yooh",
    "ARForest",
    "Reku Mochizuki",
    "Wav.AV",
    "SOTUI",
    "DJ Raisei",
    "Warak",
    "Antistar feat. Ctymax",
    "TangJuan",
    "adaptor vs DRIVE.",
    "RUQOA",
    "小红Akane，李祥晖",
    "SaMZIng",
    "Dachs",
    "litmus*",
    "NormalM feat. Usagi Denki",
    "Lundy vs. Wyvren",
    "D_AAN",
    "Acute Disarray",
    "DETRO a.k.a. ルゼ",
    "みーに",
    "R300K",
    "TAG",
    "dandeless",
    "MALVA.",
    "Asuka",
    "1112 vs. Star＊",
    "SNKS & Mizku",
    "Hinkik & A Himitsu",
    "seatrus",
    "Sakuzyo",
    "Normal1zer vs. Broken Nerdz",
    "K-forest",
    "ginkiha",
    "Nagiha",
    "Jun Kuroda",
    "S9ryne",
    "t+pazolite",
    "rider",
    "Cashew",
    "ADean & JocularACE",
    "Tatsh",
    "targ & 麻团qwq",
    "MEMME",
    "Gomadare",
    "P4koo",
    "Tetrajectory",
    "roop from STR",
    "茶鸣拾贰律",
    "LeaF",
    "レシオP",
    "Sobrem × Silentroom",
    "CrossingSound",
    "Aoi",
    "Juggernaut.",
    "かめりあ",
    "kanone vs. BlackY",
    "Sound Souler",
    "MYUKKE.",
    "PTB10",
    "Rabpit",
    "typeMARS",
    "Maozon",
    "Ponchi♪ feat. はぁち",
    "Se-U-Ra",
    "ころねぽち With 立秋",
    "Ardolf",
    "Blacklolita",
    "Dolphin",
    "nm-y & Kry.exe",
    "わかどり",
    "Iris",
    "朔(Apo11o program vs. お月さま交響曲) ft. kuroa×荒巻",
    "Paul Bazooka",
    "CNHKSS feat. 符白牙",
    "SunsetRay/NceS",
    "rareguy",
    "PRASTIK DANCEFLOOR",
    "cybermiso feat. tigerlily",
    "Finite Limit vs SiLiS",
    "Limpid",
    "月見静華 vs. LUNARiUM",
    "M2U",
    "姜米條",
    "ルゼ",
    "kozato snow",
    "Cosmograph",
    "Connexio",
    "EBIMAYO",
    "siqlo",
    "Abyss Idols",
    "U-ske feat. 棗いつき",
    "Forged Reigns",
    "Nothing But Requiem feat. Aikapin & Chiyoko",
    "P4koo feat. つゆり花鈴",
    "Normal1zer",
    "ETIA. feat. Jenga",
    "Ωμεγα",
    "Turquoise(DRIVE.+Nota)",
    "Cansol",
    "Kry.exe",
    "Nauts",
    "uma vs. モリモリあつし",
    "Grand Thaw / Rigël Theatre",
    "Ctymax feat. NceS",
    "YUE.STEVEN/uen",
    "KAH",
    "CAP3",
    "Ray Nautica & Reku Mochizuki",
    "1N6Fs",
    "Tetrajectory feat.Ctymax",
    "HyuN",
    "SCTL",
    "Itsuki",
    "EnFr",
    "MeatyRabbit & NceS",
    "DJ SHION.Y",
    "Halv",
    "Joulez",
    "Only My Black Score",
    "kanoryo",
    "Masahiro “Godspeed” Aoki",
    "李化禹",
    "WyvernP feat. Madol",
    "SunsetRay",
    "Justin Dai",
    "shadow_bling",
    "Cream vs. Daily天利",
    "ZxNX",
    "HyuN feat. Syepias",
    "SOMON",
    "FLuoRiTe/姜米條",
    "Lime",
    "PIKASONIC feat. 兰音Reine",
    "kuro",
    "KAH vs. E0ri4",
    "BelieverInYou(阿卡姆巫师)",
    "姜米條☆颶風 ~ ♫元力上人♫",
    "アリスシャッハと魔法の楽団",
    "HAMA",
    "Jungo & MAX 3 feat. 刘佳宜Snow & 幻影刃shadow",
    "闫东炜",
    "MonstDeath",
]


# 画师
DRAWER_NAME_LIST: list[str] = [
    """临时工 & 倪尔""",
    """RM Design Team (青鸟 modified)""",
    """ZG""",
    """KiTA & 一击即溃""",
    """佑木いずみ & Ctymax""",
    """祈莲""",
    """1B""",
    """久世""",
    """Eridani""",
    """阿清 (青鸟 modified)""",
    """海产""",
    """赤芽""",
    """Ctymax feat. EBIMAYO""",
    """sikkari""",
    """AriaL & 57_dayo [edited by Stelli]""",
    """月亮酱""",
    """诡异童话""",
    """汉堡""",
    """BTKCyber (青鸟 modified)""",
    """Doro-nyong & Ratif""",
    """NOISER""",
    """绀屋""",
    """masiro vs. adaptor""",
    """艾是Abby""",
    """Karameru""",
    """山崎团""",
    """Sak""",
    """Transendium""",
    """cala for Immaculée Sekai""",
    """森灵""",
    """駿""",
    """釜飯轟々丸 + jht (Design: 祈莲)""",
    """3z""",
    """手鞠鈴 & 自動車 原付""",
    """何呵""",
    """瀬名""",
    """Keiby.comics""",
    """GAMEBAKA""",
    """海里狄七 feat. 存艺""",
    """昔璃☆暴雨 ~ ♫危難聖帝♫""",
    """Taurell""",
    """ViscerA & Psycholine""",
    """Photonskyto""",
    """ASXX""",
    """YuKiMuMa""",
    """ナナシ""",
    """LINUS""",
    """rN @ 湯元画伯""",
    """knife美工刀""",
    """英英英""",
    """Lyrebird Ferdinant (青鸟&V17AMax Modified)""",
    """茶鸣拾贰律""",
    """cokeAnut""",
    """Grand Thaw / Rigël Theatre""",
    """小黄鸡叽叽叽叽叽叽修复中""",
    """谷地（青鸟 modified）""",
    """rokopon""",
    """Jeffery""",
    """叶藤""",
    """喵n葵""",
    """御坂果子""",
    """SOMON""",
    """utosao""",
    """Ctymax""",
    """Haight""",
    """Hachimitsu☆Boy""",
    """Xquid""",
    """上倉エク""",
    """林语""",
    """兜""",
    """snake.ribs""",
    """緑風マルト""",
    """笔记RE""",
    """幽灵星""",
    """あおお/A-ZERO, morph""",
    """Kyuare & Wsx""",
    """爱39的Konya""",
    """L-sp4""",
    """彗星 feat. 祈莲""",
    """TOTOTO """,
    """BLACK 0""",
    """Sin:cK for Immaculée Sekai""",
    """QueseraGames Co., Ltd.""",
    """CH""",
    """2AI4wU4""",
    """OsuMe65""",
    """わっふゑ""",
    """ディン""",
    """打雷打人（青鸟 modified）""",
    """EBIMAYO""",
    """笔记RE/海产""",
    """xperz""",
    """IvyTowers""",
    """A-Zero Project""",
    """老张""",
    """HAZUQU""",
    """winder""",
    """CEM""",
    """Optie""",
    """圆规compasses""",
    """START SEED""",
    """山山奇""",
    """Robin""",
    """NerSAN""",
    """rN""",
    """Iriss=Frantzz=s-don""",
    """シエラ (Design: 祈莲)""",
    """伊恩 (青鸟 modified)""",
    """犀牛坨动画工坊""",
    """百九十八""",
    """Spectro""",
    """艾若拉""",
    """りゅうら""",
    """Mechari (青鸟 modified)""",
    """出前 x nekomiya""",
    """inukoro""",
    """Tsuioku""",
    """Hiro vs Zeth""",
    """验光蒸鱼""",
    """EnFr""",
    """hideo""",
    """LESYEF & 藍瀬 まなみ""",
    """Jerry & OsuMe65""",
    """ADZUKI""",
    """Sand""",
    """Juice Black (青鸟 modified)""",
    """中本ひょうり""",
    """Ctymax vs. TNiK feat. 出前""",
    """青鸟""",
    """DoublePian""",
    """TNiK""",
    """MOAI WORKS""",
    """PEZZ feat. 祈莲 & CattoHato""",
    """AriaL [edited by Stelli]""",
    """鲸弑""",
    """翠冷兮""",
    """しえろ""",
    """mology (青鸟&V17AMax Modified)""",
    """Harkiadel""",
    """sa1t""",
    """群青kurara""",
    """すずか爆弾""",
    """SEGA (V17AMax modified)""",
    """geralt""",
    """Se-U-Ra""",
    """Nabom""",
    """昔璃&TNiK""",
    """自動車 原付 vs. GAMEBAKA""",
    """注射""",
    """NEKO&海产""",
    """LRAY (青鸟 modified)""",
    """塔塔""",
    """猫箱Catbox feat. 祈莲""",
    """Sodhelium""",
    """神居冰绘 feat. 祈莲""",
    """白 & 小鹏xpeng""",
    """Lanota © Noxy Games Inc. """,
    """午苔veeee~""",
    """昔璃""",
    """SCTL""",
    """Fl00t""",
    """cycat""",
    """Arahosi""",
    """子狼""",
    """Lapelristar (青鸟&V17AMax Modified)""",
    """Shimoruchiko""",
    """cycats""",
    """MHK (青鸟 modified)""",
]

# 谱师
CHARTER_LIST: list[str] = [
    """TimiTini""",
    """RDRT -p 20:02:21""",
    """Eaimo vs. CtyNer dancing wildly""",
    """thrAsh forSe""",
    """Another cat""",
    """Barbarianerman, Main theme within the somnium""",
    """Pat Brick Man Mr.C & Mr.B""",
    """Cloud Catcats""",
    """XMT小咩兔 vs. 上班睡大觉_Sleepyhead""",
    """Arenn Saki as \"lAβyrinS\"""",
    """Rikko EXPERT Lv.40""",
    """六回目Traveler Scend as \"Knight of Arq\"""",
    """クラッタ・アナザー・ラウンド""",
    """Ctymax vs. Barbarianerman""",
    """dancing\"L\"ine 2085""",
    """Gino""",
    """Pat Brick Man Mr.C""",
    """XMT小咩兔""",
    """SPΔDE & 倪尔qwq""",
    """Phigros Charting Team""",
    """Two skunks (Ctymax and 晨) in Africa shouting WAHHHHHH!""",
    """Barbarianerman fixed by Clutter""",
    """Sillyp & Alloces""",
    """with U""",
    """迟戈 vs. Likey""",
    """NerSANTA & Gausbell""",
    """Arenn Saki as \"myStery\"""",
    """LonelyKnight""",
    """Jeitie & CorruptedEntity 『Hollow』""",
    """Pcat【零】198""",
    """フィグロス譜面チーム \"Rikko feat. Ner\" -Pray for \"PHI\"-""",
    """Clutter is coppery，Tumult is coppery""",
    """M3d1uM""",
    """Salt & Barbarianerman""",
    """Ner ~ See you next time ~""",
    """IMD_0b0110""",
    """RDRT -p 19:08:31""",
    """穿山甲-1""",
    """『兔』年大吉""",
    """jeitie touches grass""",
    """Creator ~ StupiGGy""",
    """人外侵略地球计划""",
    """StuRmwind""",
    """NerSAN sipping XMTea""",
    """百九十八""",
    """Salt & Uvernight""",
    """CTYMAX ????""",
    """阿♪爽""",
    """XMT as \"eX-MentalisT\"""",
    """波之所杂""",
    """Likey & Gausbon""",
    """Ner ~Freaky Cat of Charting~""",
    """Absolute(6)""",
    """Barbarianerman vs. HaraKuma""",
    """XMT wishing upon a satellite""",
    """上班摸大鱼 a.k.a. 海洋咩兔""",
    """Clutter""",
    """Bσrbσriσn∑rmσn.∑x∑""",
    """乱流に巻き込まれ""",
    """Alloces""",
    """阿爽 eat Ctymax""",
    """Su1fuR -All about YOU & ME-""",
    """Barbarianerman & Regret""",
    """Likey affected by Ancestral Xhronicle""",
    """阿爽 fixed by Barbarianerman""",
    """while(TangScend==TangScend);""",
    """Where are Ctymax and 阿爽?""",
    """Barbarianerman vs. Uvernight""",
    """騎士 vs. Knight """,
    """雑""",
    """阿爽 fixed by Clutter""",
    """HD R.esolution""",
    """One skunk (Ctymax) in Africa""",
    """merry CNrisTimas""",
    """{Devastation,Destruction}""",
    """Executor-X""",
    """Likey feat. 198""",
    """-StupiGGy- fixed by 晨""",
    """完璧 × 北星""",
    """其三 我所存在的证明""",
    """生根发芽的小咩兔""",
    """Raiky Season""",
    """CN_115+TangScend""",
    """totally ramified COC""",
    """Hardcore Barbaya""",
    """-NerSAN & Su1fuR-""",
    """阿爽『Destroy』""",
    """jouR.ney with hold""",
    """A.S.H.""",
    """Su1fuR、快斬！""",
    """FORGET :: CLUTTER""",
    """XMT, Encore after the end""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by 晨""",
    """其二 向前迈进的理由""",
    """Salt feat. XMT小咩兔""",
    """TimiTini & HaraKuma""",
    """阿爽 vs. Ctymax -Haose 垃圾-""",
    """『流』年大顺""",
    """Simon_Axis""",
    """Ctymax vs. 晨""",
    """撕裂者『無極』 fixed by 晨""",
    """XMT小咩兔 vs. Barbarianerman""",
    """Hara小兔组""",
    """Likey & Barbarianerman""",
    """Ctymax vs. IUIsauce -村头烤鱼蘸凹酱-""",
    """Pcat""",
    """while(TangScend<=TangScend);""",
    """Ctymax vs. 阿爽""",
    """Sparkle Ctymax""",
    """Ctymax in a volcano, very delicious""",
    """Likey underground""",
    """StaR-1""",
    """R/kko""",
    """Another M3""",
    """Find_Ctymax fixed by 百九十八""",
    """Gausbon fixed by XMT""",
    """Rikko & TangScend""",
    """StR-9""",
    """\'\'-1\'\'""",
    """Nothing But Ner & Pcat""",
    """Ctymatch Girl""",
    """Ctymax after 7 years""",
    """白""",
    """SantR""",
    """Gausbon ~ See you next time ~ """,
    """Warning: XMT is infected by Trojan!!""",
    """NerSAN""",
    """vesper/straycat""",
    """Clutter & Barbarianerman""",
    """ARE YOU JEITIE!!!""",
    """inert COC""",
    """椒盐倪尔""",
    """Sillyp vs. 晨""",
    """SimonAxis""",
    """対流に巻き込まれ""",
    """Max(C,t,y)""",
    """L.I.K.E.Y.""",
    """百九十八 vs. Barbarianerman""",
    """Uvernight fixed by 百九十八""",
    """BarbariaNerSAN feat. Snorkel""",
    """Passport:Constructor""",
    """Arenn Salty feat. LDA""",
    """VikingNexus""",
    """Likey >IT\'S SHOWTIME!""",
    """Jαckψ feat. Βαρβαροςαντρας""",
    """ST AS is XMT""",
    """LuminousGausbon""",
    """□MT in a XXXXXXXX""",
    """THE LAST 198""",
    """H.C.C. fixed by Barbarinerman""",
    """StupiGGy fixed by 百九十八""",
    """Gausbon & StupiGGy""",
    """A.S.H&晨""",
    """Likey""",
    """Clutter Echo""",
    """NerSANTA vs. BarbarianerSLEDGE""",
    """Gausbon vs. XMT小咩兔""",
    """Su1fuRikko × rN \"judgemeNt fRom the cataStRophy\"""",
    """JKy as \"Stray Cat\"""",
    """Spy-Simon_Axis | Spy-騎士""",
    """Cluttler with ShelteR""",
    """Uvernight & Su1fuR""",
    """Hook vs. _鉄""",
    """逆天使の悪魔 【Likey】""",
    """CN_115 as \"prediCameNt\"""",
    """阿爽""",
    """A.S.H""",
    """RWND -p 16493:62786:92551""",
    """Divination Fortune""",
    """unDefined Future""",
    """阿爽 & 百九十八""",
    """Barbarianerman, Overture before the story""",
    """Demiurge ~ Dawn""",
    """弧光""",
    """&ikko""",
    """Arenn Saki as \"mAze\"""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by Pcat""",
    """森德雷斯 vs. 百九十八""",
    """NerSAN feat. Takanashi Rikko""",
    """N\\erry Xmas 2024""",
    """NerSAN & 百九十八""",
    """野从菠萝""",
    """J0(_)I2|\\|3y\'5 3|\\||)""",
    """Barbarvillea""",
    """AUTO. SHOOTER. fixed by Ctymax""",
    """JKy vs StrayCat""",
    """TangScend -Err0rederci-""",
    """Ctymax vs. Gausbounce""",
    """1÷98""",
    """P & U""",
    """～漂泊者～凹酱""",
    """百九十八 feat. Likey""",
    """Merry ChristymAxS""",
    """村头村头 CTY Story!!""",
    """Simon_Axis vs. Su1fuR""",
    """<= Noblesse Jeitie =>""",
    """Bariantum Hyperianerman""",
    """while(TangScend=TangScend);""",
    """Burn Full Catcats""",
    """BlindForest 『Observing』""",
    """Simon_Axis >< Likey""",
    """Eastern Ailuropoda Gang""",
    """Believe Ctymax""",
    """百九十八 busting 阿爽""",
    """Nr3_Official""",
    """jeitie goes outside""",
    """Pat Brick Man Mr.N feat. Ner of Time""",
    """4B314C3042592B45""",
    """Barbarianerman & J.R""",
    """COLORFUL BLACK GAUSBON""",
    """Rikko from「PHIGROS MOON」""",
    """B.""",
    """{Destruction}""",
    """其一 呼吸尚存的标志""",
    """RXhuang""",
    """RipHall vs. Likey""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by 野从&晨""",
    """ANGER&SORROW >^< LDA""",
    """Deep Dark Ctymax""",
    """晨 vs. XMT小咩兔""",
    """上班睡大觉_Sleepyhead""",
    """Alloces feat. Uvernight""",
    """Manufacturer ~ Rikko""",
    """StrayCat""",
    """COC  feat. Su1fuR""",
    """HCC!!!""",
    """Ner & 198 from 「PHIGROS MOON」""",
    """vacant/stupiggy""",
    """Believe TimiTini""",
    """Debut under spotlights!< Simon_Axis""",
    """ネルサン (I make charts slowly)""",
    """波""",
    """無†極""",
    """imd visual charter \"Rikko\" since 2014""",
    """奥術 ~The Empery~""",
    """reanimate_6k_nm.imd""",
    """Jαckψ""",
    """Likey & 198ar""",
    """Bear""",
    """Passport:Visitor""",
    """Bσrbσriσnermσn.exe""",
    """CorruptedEntity & 野从""",
    """曦枢 vs. 鎏光 -Lv.70 LEAF-""",
    """Affection&memories \\\\// Salt & Simon_Axis""",
    """NerSAN feat. Pcat""",
    """JKy, the inferior""",
    """Uvernight fixed by StR-1""",
    """Barbarianerman""",
    """不喜欢线的COC""",
    """Snorkel vs. NerSAN""",
    """4D45474142592B45""",
    """N\\erry Xmas""",
    """Simon_Axis•騎士•StR-1""",
    """Ctymax drives in BlindForest""",
    """Apocalyptic Dissonance""",
    """NerSANNN""",
    """Barbarianerman.exe""",
    """Eaimo fixed by NerSAN""",
    """Swing Salt ♪""",
    """N.E.R.1.9.8.""",
    """Su1fuRikko \"SouRce of the metaveRse\"""",
    """TECHNOXMT vs. LATENCYPOLIS""",
    """Crush βETA""",
    """Catcats & 百九十八 fixed by Clutter""",
    """1uminous StaR""",
    """Drop Catcats""",
    """縱連打の信者☆無極""",
    """StupiGGy""",
    """阿爽 fixed by Barbarinerman""",
    """Nothing But Likey""",
    """XMT & Salt""",
    """BarbariaNERman vs. JKy""",
    """Rikko""",
    """野从""",
    """Gausbounce""",
    """鲲 fixed by 百九十八""",
    """Clutter vs. Salt""",
    """小咩兔、参上""",
    """Barbarianerman feat. 晨""",
    """Gausbounce & 晨""",
    """N-23""",
    """Xlutter guided by three Oaths""",
    """RTH""",
    """|R|I|K|K|O| NORMAL""",
    """Barbarialid""",
    """NerSAN vs. 阿爽 『Collapse』""",
    """Future BarbarXMT""",
    """Nothing But Uvernight""",
    """-JKy-""",
    """monochrome ILLUSION""",
    """StupiGGy -The Origin-""",
    """COC""",
    """Passport:Governor""",
    """TangScend""",
    """Clutter BETA""",
    """Catcats & 百九十八""",
    """信仰の剣『生』""",
    """さるふるふるさ""",
    """COLORFUL CTYMAX""",
    """Su1fuR -FAISEURS DE PANIQUE-""",
    """杂波不是杂啵，野从不是野丛""",
    """Merry xmAS""",
    """Su1fuR vs. Simon_Axis""",
    """鲲""",
    """KillJoy""",
    """晨""",
    """亚树见希子 & 百九十八""",
    """Ctymax respect for STAR TRACK in 2008""",
    """兔咩小 VS 咩小兔 VS 小兔咩 VS 咩兔小 VS 兔小咩""",
    """Min(C,t,y)""",
    """時の希 & 百九十八""",
    """M3d1uM & 百九十八""",
    """while(TangScend>=TangScend);""",
    """完璧 vs 癒株 -Autumn Memory-""",
    """StupiGGy -The Startline-""",
    """JKy""",
    """Rikko³ [Normal]""",
    """ɹǝʇʇnlƆ""",
    """Likey & 百九十八""",
    """Believe Ctymax & TimiTini""",
    """零號宇夜""",
    """Barbarianerman feat. Gausbon""",
    """XMT is silvery, 小咩兔 is silvery""",
    """198 in Kowloon""",
    """4731474142592B45""",
    """完璧 [WARNING: DRAG OVERLOAD]""",
    """Sillyp vs. 阿爽""",
    """-Seek A Lnside Truth-""",
    """Pcat & 百九十八""",
    """Barianic Baradise""",
    """∅""",
    """Su1fuR""",
    """StuRmfeuer""",
    """Helabot""",
    """Lumiere""",
    """Likey -For an old friend-""",
    """Uvernight""",
    """啊哒咔哟 & 小咩兔 & COC""",
    """StupiGGy vs. 阿爽""",
    """SeveredEntity (BlindForest vs. rN) feat. Δ""",
    """鲲&百九十八""",
    """De Fiance""",
    """Barbarianerman vs. Snorkel""",
    """Δ (M3d1uM vs. Salt)""",
    """断罪の剣『神』""",
    """猫の信 & 百九十八""",
    """Ctymax""",
    """倪之所爽""",
    """Likey """,
    """百九十八 feat. NerSAN""",
    """晨 vs. 阿爽""",
    """XMT & 198""",
    """WhiteCat.""",
    """[!!12:l<l<ο!!]""",
    """HaraKuma""",
    """R.""",
    """Hara is golden, Kuma is golden""",
    """奇跡の希 feat. 奇跡の従""",
    """晨_鉄""",
    """扫佛不是嫂夫""",
    """_鉄 (Isotope 59)""",
    """無彩色""",
    """平川の剣『士』""",
    """Ner, the inferior""",
    """晨 vs. Ctymax""",
    """空の希""",
    """Salt""",
    """ƃuɐnɥs∀ .sʌ uoqsnɐ⅁""",
    """Timi今天吃神马""",
    """Gausbon""",
    """J.R""",
    """急流に巻き込まれ""",
    """分化者 fixed by Barbarianerman""",
    """Sparkle Ctymax fixed by 百九十八""",
    """Яadiance""",
    """RDRT -p 20:08:31""",
    """爽夜讃歌""",
    """夜明の剣『靈』""",
    """Barbarianerman vs. Alloces""",
    """{Demolition,Devastation,Destruction}""",
    """Knight""",
    """Ctymax vs. 阿爽  fixed by B B M pow""",
    """StR-1""",
    """Pcat『Scatter』""",
    """Blessing beyond my""",
    """iv""",
    """TimiTini →\"X\"← 阿爽""",
    """NerSAN vs. 阿爽""",
    """Doubt Ful""",
    """Rikko & 198""",
    """LDAJOY&PLEASANT ^V^ LDA""",
    """孤独な騎士 Against 魔王、大咩兔""",
    """Gausbon feat. 迟戈&野从""",
    """merry XM AS""",
    """Ner as \"SPΔDE\"""",
    """BlindForest""",
    """無極☆雷鳴 ~ ♫死の序曲♫""",
    """不喜欢键的COC""",
    """Arenn Saki vs. NerSAN""",
    """Find_Ctymax""",
    """Barbarianerman & NerSAN in the ICU""",
    """Ctymax vs. 百九十八""",
    """壹號阿爽""",
    """jouR.ney to the end【COVERED】""",
    """Sempiternal Fxxxxxx Resolution!""",
    """Jeitie""",
    """Salt & _鉄 inspired by 存在証明 [X]""",
    """ParParianerman""",
    """Brave Eaimo""",
    """B.A.R.B.A.R.I.A.N.E.R.M.A.N.""",
    """光る星""",
    """云正太""",
    """Barbarianerman vs. NerSAN""",
    """Sillyp""",
    """撕裂者『Alloces vs. Shin』""",
    """Myna feat.Sleepyhead""",
    """jeitie gets sent to the sun""",
    """Another Stage""",
    """_鉄""",
    """C.Max (PBM)""",
    """头鱼头鱼 MAX Story!!""",
    """h.o.m.e.e.e.""",
    """B.B.M.""",
    """六回目Traveler Scend""",
    """逆流而上的小咩兔""",
    """Arenn Saki vs. Catcats vs. 百九十八""",
    """R:kko (IMD)""",
    """Cty moyules""",
    """b.b.n.m.""",
    """Stray Cat Around""",
    """実戦 with Rikko""",
    """StupiGGy vs. 百九十八 ft. 野从""",
    """BLACK CTYMAX""",
    """IMD_6""",
    """Jαckψ a.k.a JKy""",
    """NerSAN vs. Ctymax as \"泥头鱼\"""",
    """XMT小咩兔 & Myna""",
    """Gausbon vs. 阿爽""",
    """We are the Miserable""",
    """Latency, Finale of the dream""",
    """StR-1 watches Ctyfilm""",
    """Burn Full Catcats vs. Ctymatch Girl""",
    """Snorkel""",
    """IUIsauce""",
    """OPENING/Level R""",
    """2B45524142592B45""",
    """Ctymax but 5 years later""",
    """s.t.p.g.""",
    """無†極 fixed by Rikko""",
    """Ner＜Jazz for your soul .)""",
    """NerSANN""",
    """奇跡の希""",
]

# 组合名称;
COMBINE_NAME: list[str] = [
    "introduction",
    "Glaciaxion.SunsetRay",
    "EradicationCatastrophe.NceS",
    "Credits.Frums",
    "Dlyrotz.Likey",
    "EnginexStartmelodymix.CrossingSound",
    "光.姜米條",
    "Wintercube.CtymaxfeatNceS",
    "Cipher20.TetrajectoryfeatCtymax",
    "混乱Confusion.OnlyMyBlackScore",
    "FULiAUTOSHOOTER.MYUKKE",
    "HumaN.SOTUI",
    "PRAW.Bluewind",
    "PixelRebelz.Normal1zer",
    "Cereris.SunsetRayNceS",
    "NonMelodicRagezMUGEdit.Normal1zer",
    "SultanRage.MonstDeath",
    "ClassMemories.AntistarfeatCtymax",
    "SURREALISM.Itsuki",
    "BonusTime.MegaloPaleWhite",
    "ENERGYSYNERGYMATRIX.Tanchiky",
    "NYA.FLuoRiTe姜米條",
    "JunXionBetweenLifeAndDeathVIPMix.1N6Fs",
    "cryout.JuE",
    "Reimei.影虎",
    "尊師TheGuru.rider",
    "Spasmodic.姜米條颶風元力上人",
    "LeaveAllBehind.rider",
    "ColorfulDays.P4koofeatつゆり花鈴",
    "microwav.dandeless",
    "重生.姜米條",
    "NOONEYESMAN.MYUKKE",
    "望影の方舟Six.SeURa",
    "Igallta.SeURa",
    "ClockParadox.WyvernP",
    "Chronologika.Hundotte",
    "NickofTime.P4koo",
    "Chronomia.Lime",
    "ChronosCollapseLaCampanella.SunsetRay",
    "Rrharil.TeamGrimoire",
    "CraveWave.LandRoot",
    "TheChariotREVIIVAL.Attoclef",
    "Luminescence.米虾Fomiki初云CLoudie",
    "Retribution.nmyKryexe",
    "DESTRUCTION321.Normal1zervsBrokenNerdz",
    "DistortedFate.Sakuzyo",
    "Doppelganger.LeaF",
    "もぺもぺ.LeaF",
    "MARENOL.LeaF",
    "萤火虫の怨.闫东炜",
    "万吨匿名信.闫东炜",
    "风屿.闫东炜",
    "dBdoll.YUESTEVENuen",
    "Dash.小红Akane李祥辉",
    "云女孩.符白牙SiYFics",
    "DropIt.Asuka",
    "RIPPER.Friedwav",
    "Aphasia.闫东炜",
    "开心病.闫东炜",
    "華灯爱.闫东炜",
    "FindMe.Kforest",
    "Sein.朔Apo11oprogramvsお月さま交響曲ftkuroa荒巻",
    "狂喜蘭舞.LeaF",
    "SparkleNewLife.rider",
    "KhronostasisKatharsis.Halv",
    "SnowDesert.WyvernP",
    "Burn.NceS",
    "Aleph0.LeaF",
    "NextTime.SaMZIng",
    "RubbishSorting.CtymaxvsNceS",
    "AnotherMe.NeutralMoon",
    "mechanted.rareguy",
    "lifeflashesbeforeweebeyes.BilliumMoto",
    "BreakThroughTheBarrier.lixound",
    "Chronostasis.黒皇帝",
    "DeadSoul.SoundSouler",
    "InfinityHeaven.HyuN",
    "Disorder.HyuNfeatYURI",
    "CROSSSOUL.HyuNfeatSyepias",
    "SpeedUp.DarTokki",
    "MagentaPotion.EmoCo",
    "GetBack.CAP3",
    "Palescreen.WyvernPfeatMadol",
    "GOODTEK.EBIMAYO",
    "GOODBOUNCE.EBIMAYO",
    "GOODWORLD.EBIMAYO",
    "GOODFORTUNE.EBIMAYO",
    "GOODRAGE.EBIMAYO",
    "TheMountainEater.PaulBazooka",
    "Orthodox.tokiwa",
    "EndMe.ZxNXasDelaina",
    "ParallelRetrogressionGameVer.Tetrajectory",
    "Starduster.Quree",
    "Electron.ElousFZ",
    "SIGMA.Kryexe",
    "HardcoreKwaya.EnFr",
    "Aventyr.GrandThawRigelTheatre",
    "Trane.MALVA",
    "雪降りメリクリ.A39",
    "CervelleConnexion.SCTL",
    "modulus.PTB10",
    "Wavetapper.Frums",
    "大和撫子WildDances.adapatorvsDRIVE",
    "Eltaw.Fl00t",
    "Initialize.iF",
    "桜樹街道.kozatosnow",
    "GetReady.iF",
    "volcanic.DETROakaルゼ",
    "BetterGraphicAnimation.ルゼ",
    "XING.ginkiha",
    "FinalStep.Lime",
    "Cthugha.USAO",
    "WithYou.Cashew",
    "UnorthodoxThoughts.Joulez",
    "Apocalyptic.ZClaxxSumaiLight",
    "游园地.椒盐菠萝",
    "energytrixxx.KAH",
    "Nhelv.Silentroom",
    "Arkhei.SeraAmagi",
    "Kerberos.Zris",
    "parsey.siqlo",
    "Concvssion.Halv",
    "ジングルベルJingleBell.A39沙包P",
    "TimetoNightSkyfeatLeeYuJin.HyuNKLYDIX",
    "HAZARD.Limpid",
    "AnotherMe.DAAN",
    "DontNeverAround.HAMA",
    "RESSiSTANCE.ぐるたみん",
    "Dreamland.z1onkyrrin",
    "AnotherRound.JustinDai",
    "996.李化禹",
    "FutureMind.RayNauticaRekuMochizuki",
    "Luminescent.Daison",
    "FULiAUTOBUSTER.MYUKKE",
    "IMustSayNo.TangJuan",
    "opia.rN",
    "Apocalypse.アリスシャッハと魔法の楽団",
    "Protoflicker.Silentroom",
    "HorizonBlue.NothingButRequiemfeatAikapinChiyoko",
    "YouaretheMiserable.tpazolite",
    "Stasis.Maozon",
    "いざ参ります.Uskefeat棗いつき",
    "月下缭乱.月見静華vsLUNARiUM",
    "OnAndOn.ETIAfeatJenga",
    "DataErr0r.Cosmograph",
    "Shadow.SumaiLightvs姜米條",
    "心之所向.姜米條",
    "inferior.姜米條",
    "csqn.Aoi",
    "BraveNotes.TurquoiseDRIVENota",
    "盏茗.茶鸣拾贰律",
    "青芽.茶鸣拾贰律",
    "EternalSnow.AbyssIdols",
    "RainySeason.AbyssIdols",
    "ElCondorPasaPhigrosEdit.PlasticFruits",
    "BreakOver.Kforest",
    "BelieveLightfeat果丸哒呦.ScalerMestie果丸哒呦",
    "Pontdessouvenirs.VeetaCrushvsitsufeatitsu",
    "青丘.BLACK0",
    "瓷岁.茶鸣拾贰律",
    "Feast远东之宴.茶鸣拾贰律",
    "インフェルノシティ.Ponchifeatはぁち",
    "Upshift.Iriss-Frantzz",
    "PoisonANDORAffection.LeaF",
    "Random.SobremSilentroom",
    "零號車輛.seatrus",
    "NowIsTheTimeDoIt.RoyMikelate",
    "Bougainvillea.Jade",
    "神話.PicaM2U",
    "Elúltimobaile.Θ",
    "Trojan.litmus",
    "TemporalShifting.LureRabbitVC",
    "Adastraperaspera.RabbitHouse",
    "Ajourneytothemoonlight.Yesod",
    "RainyHeart.BelieverInYou阿卡姆巫师",
    "Realms.HinkikAHimitsu",
    "ぱぴぷぴぷぴぱ.ころねぽちWith立秋",
    "TriumphRegret.typeMARS",
    "SATELLITE.かめりあ",
    "DancewithSilence.かめりあ",
    "LabyrinthinKowloonWalledWorld.かめりあ",
    "ComputeItWithSomeDevilishAlcoholicSteampunkEngines.かめりあ",
    "ERABYECONNEC10N.かめりあ",
    "DiamondEyes.SYNTHETIC",
    "Bitterblossom.imvi",
    "SilenceisGoldenSpeechisGolden.NIWASHI",
    "FracturedAngel.DJRaisei",
    "JourneywithYou.Iris",
    "SecretIllumination.Yooh",
    "InvertedWorld.ARForest",
    "月詠に鳴る.Feryquitousfeat藍月なくる",
    "TECHNOPOLIS2085.PRASTIKDANCEFLOOR",
    "祈-我ら神祖と共に歩む者なり-.光吉猛修VS穴山大輔VSKaiVS水野健治VS大国奏音",
    "bye.DingerBox",
    "聖夜讃歌.A39沙包P",
    "ストレイソウルアラウンド.みーに",
    "ManifoldHypothesis.cybermisofeattigerlily",
    "KMoeVIP.ZxNX",
    "GVNGlitterVomitusandNeon.SaltySaltUnfold33",
    "CrushBETA.shadow_bling",
    "BrokenSky.JungoMAX3feat刘佳宜Snow幻影刃shadow",
    "BRAINHACKER.SOMON",
    "Xenolith.Tatsh",
    "ArtificialExistence.JunKuroda",
    "IndelibleScar.Noah",
    "Antithese.Blacklolita",
    "PRAGMATISMRESURRECTION.Laur",
    "ShineAfter.ADeanJocularACE",
    "Bloom.targ麻团qwq",
    "幽世桔梗.Capchiifeatまるもこ",
    "千紫万紅.r0yvsWABI",
    "明鏡烈火.MUEvsRekuMochizuki",
    "今天不是明天.PIKASONICfeat兰音Reine",
    "Cuvism.Fl00tvsHalv",
    "iLArtifact.Link0",
    "atruthseekerCommunicationwithUtopiawillbelost.kuro",
    "BoundedQuietude.FiniteLimitvsSiLiS",
    "君往何处QuoVadis.M2U",
    "暗夜苏醒REANIMATE.Warak",
    "Grimheart.Puru",
    "Thrashforce.KAHvsE0ri4",
    "Originally.SNKSMizku",
    "黄金之城GOLDTOWN.Memme",
    "双重间谍DoubleAgent.WAVAV",
    "幻影鬼魅PLEASE.R300K",
    "Schadenfreude.ZxNX",
    "Letempsperdu.Daison",
    "FixationsTowardtheStars.Foodbot",
    "valorstarcross.LundyvsWyvren",
    "CometFeat符白牙.CNHKSS",
    "白と黒のバケモノ.テヅカ",
    "Devotion.Connexio",
    "KirakiraNoelStory.RekuMochizuki",
    "Shelter.MeatyRabbitNceS",
    "蝎虎天体Lacertid.CreamvsDaily天利",
    "贝多芬祝福BeethovenBlessing.Nauts",
    "インマイマインド.レシオP",
    "ニライカナイNiraicA_naiMix.roopfromSTR",
    "SwingSkipDrop.ミハイル",
    "宇宙残骸少女CosmicDustyGirl.辻原一郎",
    "Resolver.Gomadare",
    "LuminousEntitiesLostHeart.NormalMfeatUsagiDenki",
    "KIZUNAResolution.TAG",
    "AbsoluTedisoRdeR.AcuteDisarray",
    "AphroditesChildshortver.RUQOA",
    "DevIAtiOnshortver.polysha",
    "NOx.Juggernaut",
    "Aliceinaxxxxxxxx.Nagiha",
    "Radiance.Nhato",
    "DiamondDust.MasahiroGodspeedAoki",
    "StardustRAY.kanonevsBlackY",
    "FrozenHeart.A39沙包P",
    "Helios.NOABotaNya",
    "FlutterEcho.Cansol",
    "Rebirth.ああああ",
    "AvataarReincarnationofKalpa.ScarletteakaCrYmson",
    "Poseidon.1112vsStar",
    "WATER.A39沙包P",
    "MiracleForestVIPMix.Rinthlive",
    "MOBILYS.Dachs",
    "Lyrith迷宮リリス.ユメミド",
    "Demiurge.Rabpit",
    "Demonkin.ForgedReigns",
    "Re_NascencePsystyleVer.Rinth_live",
    "Ark.kanoryo",
    "AfterDawn.S9ryne",
    "INFiNiTEENERZYOverdoze.RekuMochizuki",
    "Khalid.Dolphin",
    "QuantumHyperspace.D_AAN",
    "FreakyUndulationsNobleKnightsofTune.JehezukielKURORAK",
    "PANICPARADISE.DJSHIONY",
    "ReEndofaDream.umavsモリモリあつし",
    "心の記憶.A39沙包P",
    "Spotlight.Ardolf",
    "NightTheater.わかどり",
    "Ramification.rareguyReina",
    "DerRichter.Ωμεγα",
    "ATHAZA.LeaF",
]

MAX_LEVEL: float = 17.6  # 当前版本最高定数

# ----- 获取分组信息 -----
GROUP_INFO = {}
TAG_INFO = {}
COMMENT_INFO = {}

try:
    df = pd.read_csv(
        GROUP_PATH,
        sep=",",
        header=None,
        encoding="utf-8",
        names=["c_name", "group"],
    )
    df = df.fillna("")
    df.set_index(df.columns[0], inplace=True)
    used_group = set()
    for idx, row in df.iterrows():
        GROUP_INFO[idx] = str(row["group"])
        group_raw = str(row["group"]).strip()
        for groupi in group_raw.split("`"):
            if groupi:
                used_group.add(groupi)
    used_group = list(used_group)
except Exception:
    GROUP_INFO = {}
    used_group = []

# ----- 获取标签信息 -----
try:
    df = pd.read_csv(
        TAG_PATH,
        sep=",",
        header=None,
        encoding="utf-8",
        names=["c_name", "tag"],
    )
    df = df.fillna("")
    df.set_index(df.columns[0], inplace=True)
    used_tag = set()
    for idx, row in df.iterrows():
        TAG_INFO[idx] = str(row["tag"])
        tag_raw = str(row["tag"]).strip()
        for tagi in tag_raw.split("`"):
            if tagi:
                used_tag.add(tagi)
    used_tag = list(used_tag)
except Exception:
    TAG_INFO = {}
    used_tag = []

# ----- 获取简评信息 -----
try:
    df = pd.read_csv(
        COMMENT_PATH,
        sep=",",
        header=None,
        encoding="utf-8",
        names=[
            "c_name",
            "EZ_comment",
            "HD_comment",
            "IN_comment",
            "AT_comment",
        ],
    )
    df = df.fillna("")
    df.set_index(df.columns[0], inplace=True)
    for idx, row in df.iterrows():
        COMMENT_INFO[idx] = {
            "EZ": str(row["EZ_comment"]),
            "HD": str(row["HD_comment"]),
            "IN": str(row["IN_comment"]),
            "AT": str(row["AT_comment"]),
        }
except Exception:
    COMMENT_INFO = {}

# End of consts.py
