from src.utils.base import *

# 默认路径
# 整个文件的相对路径前缀
if debug:
    FILE_PATH = "python/rhythmgame_database/"
else:
    FILE_PATH = ""

# 主文件夹下的文件可以直接写
# 固定的运行依赖文件夹
ASSETS_PREPATH = FILE_PATH + "assets/"

DATA_PREPATH = ASSETS_PREPATH + "data/"

DEFAULT_COMMENT = DATA_PREPATH + "default_comment.csv"  # 空白简评文件
DEFAULT_GROUP = DATA_PREPATH + "default_group.csv"
DIFFICULTY_PATH = DATA_PREPATH + "difficulty.tsv"  # 各个歌曲难度文件
INFO_PATH = DATA_PREPATH + "info.tsv"  # 组合名称与拆分名称对应关系文件
NOTE_COUNT_PATH = (
    DATA_PREPATH + "note_count.csv"
)  # 每个歌曲及难度对应的各种键型数量及总合

# 字体文件
FONT_PREPATH = ASSETS_PREPATH + "font/"

EN_FONT1_PATH = FONT_PREPATH + "Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf"
NUM_FONT1_PATH = FONT_PREPATH + "Share_Tech_Mono/ShareTechMono-Regular.ttf"
CHI_FONT1_PATH = resource_path(
    FONT_PREPATH + "Source Han Sans & Saira Hybrid-Regular #5446.ttf"
)

# 图片素材(images)文件夹下文件的路径前缀
IMG_PREPATH = ASSETS_PREPATH + "images/"

# 头像图片路径前缀
AVATER_IMG_PREPATH = IMG_PREPATH + "avatars/"

# 各种小图标
ICON_PREPATH = IMG_PREPATH + "icons/"

RESET_PATH = ICON_PREPATH + "reset.png"
SAVE_ICON_PATH = ICON_PREPATH + "save.png"
FILTER_ICON_PATH = ICON_PREPATH + "filter.png"
FILTER_AGAIN_ICON_PATH = ICON_PREPATH + "filter_again.png"
QRCODE_EMPTY_IMG_PATH = ICON_PREPATH + "QRcode_empty.jpg"

# 各个评级的图标
SCORE_LEVEL_ICONS_PREPATH = ICON_PREPATH + "score_level_icons/"

SCORE_LEVEL_PATH = {
    score_level_type.F: SCORE_LEVEL_ICONS_PREPATH + "F.png",
    score_level_type.C: SCORE_LEVEL_ICONS_PREPATH + "C.png",
    score_level_type.B: SCORE_LEVEL_ICONS_PREPATH + "B.png",
    score_level_type.A: SCORE_LEVEL_ICONS_PREPATH + "A.png",
    score_level_type.S: SCORE_LEVEL_ICONS_PREPATH + "S.png",
    score_level_type.V: SCORE_LEVEL_ICONS_PREPATH + "V.png",
    score_level_type.VFC: SCORE_LEVEL_ICONS_PREPATH + "VFC.png",
    score_level_type.phi: SCORE_LEVEL_ICONS_PREPATH + "phi.png",
}

# 各种背景
BACKGROUND_IMG_PREPATH = "backgrounds/"
READONLY_BACKGROUND_IMG_PREPATH = IMG_PREPATH + "backgrounds/"

SONG_CARD_BACKGROUND = {  # 用途 作为背景区分不同难度 表示玩家挑战模式的等级
    "EZ": READONLY_BACKGROUND_IMG_PREPATH + "green-EZ.png",
    "HD": READONLY_BACKGROUND_IMG_PREPATH + "blue-HD.png",
    "IN": READONLY_BACKGROUND_IMG_PREPATH + "red-IN.png",
    "AT": READONLY_BACKGROUND_IMG_PREPATH + "gold-AT.png",
    "white": READONLY_BACKGROUND_IMG_PREPATH + "white.png",
    "colorful": READONLY_BACKGROUND_IMG_PREPATH + "colorful.png",
}

# 曲绘
ILLUSTRATION_PREPATH = IMG_PREPATH + "illustrations/"

# -----------------------------------------------------

UPDATE_PREPATH = FILE_PATH + "src/core/update/"
OUTPUT_PATH = UPDATE_PREPATH + "output.txt"


TOKEN_PATH = "session_token.json"  # 玩家session_token存储路径
SETTING_PATH = "PhiFilterTool_setting.json"  # 玩家设置

GROUP_PATH = "group.csv"  # 玩家自定义分组信息存储路径
COMMENT_PATH = "comment.csv"  # 玩家自定义简评信息存储路径


# 可作为筛选依据的属性
FILTER_ATTRIBUTION_LIST: list[str] = [
    "acc",
    "单曲rks",
    "得分",
    "定数",
    "评级",
    "难度",
    "曲名",
    "曲师",
    "谱师",
    "画师",
    # "分组",
    # "简评",
]

# 数值类比较
NUMERIC_COMPARATORS: list[str] = [
    "大于",
    "大于等于",
    "小于",
    "小于等于",
    "等于",
    "不等于",
]

# 精确 模糊比较
LOGICAL_OPERATORS: list[str] = ["等于", "不等于", "包含", "不包含"]

MAX_LEVEL: float = 17.6  # 当前版本最高定数


# ------------------ 缓存内容 --------------------
# 组合名称
COMBINE_NAME: list[str] = [
    """Glaciaxion.SunsetRay""",
    """EradicationCatastrophe.NceS""",
    """Credits.Frums""",
    """Dlyrotz.Likey""",
    """EnginexStartmelodymix.CrossingSound""",
    """光.姜米條""",
    """Wintercube.CtymaxfeatNceS""",
    """Cipher20.TetrajectoryfeatCtymax""",
    """混乱Confusion.OnlyMyBlackScore""",
    """FULiAUTOSHOOTER.MYUKKE""",
    """HumaN.SOTUI""",
    """PRAW.Bluewind""",
    """PixelRebelz.Normal1zer""",
    """Cereris.SunsetRayNceS""",
    """NonMelodicRagezMUGEdit.Normal1zer""",
    """SultanRage.MonstDeath""",
    """ClassMemories.AntistarfeatCtymax""",
    """SURREALISM.Itsuki""",
    """BonusTime.MegaloPaleWhite""",
    """ENERGYSYNERGYMATRIX.Tanchiky""",
    """NYA.FLuoRiTe姜米條""",
    """JunXionBetweenLifeAndDeathVIPMix.1N6Fs""",
    """cryout.JuE""",
    """Reimei.影虎""",
    """尊師TheGuru.rider""",
    """Spasmodic.姜米條颶風元力上人""",
    """LeaveAllBehind.rider""",
    """ColorfulDays.P4koofeatつゆり花鈴""",
    """microwav.dandeless""",
    """重生.姜米條""",
    """NOONEYESMAN.MYUKKE""",
    """望影の方舟Six.SeURa""",
    """Igallta.SeURa""",
    """ClockParadox.WyvernP""",
    """Chronologika.Hundotte""",
    """NickofTime.P4koo""",
    """Chronomia.Lime""",
    """ChronosCollapseLaCampanella.SunsetRay""",
    """Rrharil.TeamGrimoire""",
    """CraveWave.LandRoot""",
    """TheChariotREVIIVAL.Attoclef""",
    """Luminescence.米虾Fomiki初云CLoudie""",
    """Retribution.nmyKryexe""",
    """DESTRUCTION321.Normal1zervsBrokenNerdz""",
    """DistortedFate.Sakuzyo""",
    """Doppelganger.LeaF""",
    """もぺもぺ.LeaF""",
    """MARENOL.LeaF""",
    """萤火虫の怨.闫东炜""",
    """万吨匿名信.闫东炜""",
    """风屿.闫东炜""",
    """dBdoll.YUESTEVENuen""",
    """Dash.小红Akane李祥辉""",
    """云女孩.符白牙SiYFics""",
    """DropIt.Asuka""",
    """RIPPER.Friedwav""",
    """Aphasia.闫东炜""",
    """开心病.闫东炜""",
    """華灯爱.闫东炜""",
    """FindMe.Kforest""",
    """Sein.朔Apo11oprogramvsお月さま交響曲ftkuroa荒巻""",
    """狂喜蘭舞.LeaF""",
    """SparkleNewLife.rider""",
    """KhronostasisKatharsis.Halv""",
    """SnowDesert.WyvernP""",
    """Burn.NceS""",
    """Aleph0.LeaF""",
    """NextTime.SaMZIng""",
    """RubbishSorting.CtymaxvsNceS""",
    """AnotherMe.NeutralMoon""",
    """mechanted.rareguy""",
    """lifeflashesbeforeweebeyes.BilliumMoto""",
    """BreakThroughTheBarrier.lixound""",
    """Chronostasis.黒皇帝""",
    """DeadSoul.SoundSouler""",
    """InfinityHeaven.HyuN""",
    """Disorder.HyuNfeatYURI""",
    """CROSSSOUL.HyuNfeatSyepias""",
    """SpeedUp.DarTokki""",
    """MagentaPotion.EmoCo""",
    """GetBack.CAP3""",
    """Palescreen.WyvernPfeatMadol""",
    """GOODTEK.EBIMAYO""",
    """GOODBOUNCE.EBIMAYO""",
    """GOODWORLD.EBIMAYO""",
    """GOODFORTUNE.EBIMAYO""",
    """GOODRAGE.EBIMAYO""",
    """TheMountainEater.PaulBazooka""",
    """Orthodox.tokiwa""",
    """EndMe.ZxNXasDelaina""",
    """ParallelRetrogressionGameVer.Tetrajectory""",
    """Starduster.Quree""",
    """Electron.ElousFZ""",
    """SIGMA.Kryexe""",
    """HardcoreKwaya.EnFr""",
    """Aventyr.GrandThawRigelTheatre""",
    """Trane.MALVA""",
    """雪降りメリクリ.A39""",
    """CervelleConnexion.SCTL""",
    """modulus.PTB10""",
    """Wavetapper.Frums""",
    """大和撫子WildDances.adapatorvsDRIVE""",
    """Eltaw.Fl00t""",
    """Initialize.iF""",
    """桜樹街道.kozatosnow""",
    """GetReady.iF""",
    """volcanic.DETROakaルゼ""",
    """BetterGraphicAnimation.ルゼ""",
    """XING.ginkiha""",
    """FinalStep.Lime""",
    """Cthugha.USAO""",
    """WithYou.Cashew""",
    """UnorthodoxThoughts.Joulez""",
    """Apocalyptic.ZClaxxSumaiLight""",
    """游园地.椒盐菠萝""",
    """energytrixxx.KAH""",
    """Nhelv.Silentroom""",
    """Arkhei.SeraAmagi""",
    """Kerberos.Zris""",
    """parsey.siqlo""",
    """Concvssion.Halv""",
    """ジングルベルJingleBell.A39沙包P""",
    """TimetoNightSkyfeatLeeYuJin.HyuNKLYDIX""",
    """HAZARD.Limpid""",
    """AnotherMe.DAAN""",
    """DontNeverAround.HAMA""",
    """RESSiSTANCE.ぐるたみん""",
    """Dreamland.z1onkyrrin""",
    """AnotherRound.JustinDai""",
    """996.李化禹""",
    """FutureMind.RayNauticaRekuMochizuki""",
    """Luminescent.Daison""",
    """FULiAUTOBUSTER.MYUKKE""",
    """IMustSayNo.TangJuan""",
    """opia.rN""",
    """Apocalypse.アリスシャッハと魔法の楽団""",
    """Protoflicker.Silentroom""",
    """HorizonBlue.NothingButRequiemfeatAikapinChiyoko""",
    """YouaretheMiserable.tpazolite""",
    """Stasis.Maozon""",
    """いざ参ります.Uskefeat棗いつき""",
    """月下缭乱.月見静華vsLUNARiUM""",
    """OnAndOn.ETIAfeatJenga""",
    """DataErr0r.Cosmograph""",
    """Shadow.SumaiLightvs姜米條""",
    """心之所向.姜米條""",
    """inferior.姜米條""",
    """csqn.Aoi""",
    """BraveNotes.TurquoiseDRIVENota""",
    """盏茗.茶鸣拾贰律""",
    """青芽.茶鸣拾贰律""",
    """EternalSnow.AbyssIdols""",
    """RainySeason.AbyssIdols""",
    """ElCondorPasaPhigrosEdit.PlasticFruits""",
    """BreakOver.Kforest""",
    """BelieveLightfeat果丸哒呦.ScalerMestie果丸哒呦""",
    """Pontdessouvenirs.VeetaCrushvsitsufeatitsu""",
    """青丘.BLACK0""",
    """瓷岁.茶鸣拾贰律""",
    """Feast远东之宴.茶鸣拾贰律""",
    """インフェルノシティ.Ponchifeatはぁち""",
    """Upshift.Iriss-Frantzz""",
    """PoisonANDORAffection.LeaF""",
    """Random.SobremSilentroom""",
    """零號車輛.seatrus""",
    """NowIsTheTimeDoIt.RoyMikelate""",
    """Bougainvillea.Jade""",
    """神話.PicaM2U""",
    """Elúltimobaile.Θ""",
    """Trojan.litmus""",
    """TemporalShifting.LureRabbitVC""",
    """Adastraperaspera.RabbitHouse""",
    """Ajourneytothemoonlight.Yesod""",
    """RainyHeart.BelieverInYou阿卡姆巫师""",
    """Realms.HinkikAHimitsu""",
    """ぱぴぷぴぷぴぱ.ころねぽちWith立秋""",
    """TriumphRegret.typeMARS""",
    """SATELLITE.かめりあ""",
    """DancewithSilence.かめりあ""",
    """LabyrinthinKowloonWalledWorld.かめりあ""",
    """ComputeItWithSomeDevilishAlcoholicSteampunkEngines.かめりあ""",
    """ERABYECONNEC10N.かめりあ""",
    """DiamondEyes.SYNTHETIC""",
    """Bitterblossom.imvi""",
    """SilenceisGoldenSpeechisGolden.NIWASHI""",
    """FracturedAngel.DJRaisei""",
    """JourneywithYou.Iris""",
    """SecretIllumination.Yooh""",
    """InvertedWorld.ARForest""",
    """月詠に鳴る.Feryquitousfeat藍月なくる""",
    """TECHNOPOLIS2085.PRASTIKDANCEFLOOR""",
    """祈-我ら神祖と共に歩む者なり-.光吉猛修VS穴山大輔VSKaiVS水野健治VS大国奏音""",
    """bye.DingerBox""",
    """聖夜讃歌.A39沙包P""",
    """ストレイソウルアラウンド.みーに""",
    """ManifoldHypothesis.cybermisofeattigerlily""",
    """KMoeVIP.ZxNX""",
    """GVNGlitterVomitusandNeon.SaltySaltUnfold33""",
    """CrushBETA.shadow_bling""",
    """BrokenSky.JungoMAX3feat刘佳宜Snow幻影刃shadow""",
    """BRAINHACKER.SOMON""",
    """Xenolith.Tatsh""",
    """ArtificialExistence.JunKuroda""",
    """IndelibleScar.Noah""",
    """Antithese.Blacklolita""",
    """PRAGMATISMRESURRECTION.Laur""",
    """ShineAfter.ADeanJocularACE""",
    """Bloom.targ麻团qwq""",
    """幽世桔梗.Capchiifeatまるもこ""",
    """千紫万紅.r0yvsWABI""",
    """明鏡烈火.MUEvsRekuMochizuki""",
    """今天不是明天.PIKASONICfeat兰音Reine""",
    """Cuvism.Fl00tvsHalv""",
    """iLArtifact.Link0""",
    """atruthseekerCommunicationwithUtopiawillbelost.kuro""",
    """BoundedQuietude.FiniteLimitvsSiLiS""",
    """君往何处QuoVadis.M2U""",
    """暗夜苏醒REANIMATE.Warak""",
    """Grimheart.Puru""",
    """Thrashforce.KAHvsE0ri4""",
    """Originally.SNKSMizku""",
    """黄金之城GOLDTOWN.Memme""",
    """双重间谍DoubleAgent.WAVAV""",
    """幻影鬼魅PLEASE.R300K""",
    """Schadenfreude.ZxNX""",
    """Letempsperdu.Daison""",
    """FixationsTowardtheStars.Foodbot""",
    """valorstarcross.LundyvsWyvren""",
    """CometFeat符白牙.CNHKSS""",
    """白と黒のバケモノ.テヅカ""",
    """Devotion.Connexio""",
    """KirakiraNoelStory.RekuMochizuki""",
    """Shelter.MeatyRabbitNceS""",
    """蝎虎天体Lacertid.CreamvsDaily天利""",
    """贝多芬祝福BeethovenBlessing.Nauts""",
    """インマイマインド.レシオP""",
    """ニライカナイNiraicA_naiMix.roopfromSTR""",
    """SwingSkipDrop.ミハイル""",
    """宇宙残骸少女CosmicDustyGirl.辻原一郎""",
    """Resolver.Gomadare""",
    """LuminousEntitiesLostHeart.NormalMfeatUsagiDenki""",
    """KIZUNAResolution.TAG""",
    """AbsoluTedisoRdeR.AcuteDisarray""",
    """AphroditesChildshortver.RUQOA""",
    """DevIAtiOnshortver.polysha""",
    """NOx.Juggernaut""",
    """Aliceinaxxxxxxxx.Nagiha""",
    """Radiance.Nhato""",
    """DiamondDust.MasahiroGodspeedAoki""",
    """StardustRAY.kanonevsBlackY""",
    """FrozenHeart.A39沙包P""",
    """Helios.NOABotaNya""",
    """FlutterEcho.Cansol""",
    """Rebirth.ああああ""",
    """AvataarReincarnationofKalpa.ScarletteakaCrYmson""",
    """雪降り雪が降っている.AiSSw夜輪ft結月ゆかり""",
    """RetributionCycleofRedemption.ArdolfvsDaily天利""",
    """アンビバレンス.すりぃ相沢""",
    """Komplexe.雄之助featSennzai""",
    """slips.rintarosoma""",
    """QZKagoRequiem.tpazolite""",
    """SolaggyfeatUzumaki.ShrimpCatsはぁち後藤涼輔""",
    """000AinSophAur.Yumeji""",
    """Xepion.Acotto""",
    """Archidoxen.Se_IRA""",
    """百鬼夜行.SaladSavior""",
    """BANGINGSTRIKE.DewPleiades""",
    """TheWholeRest.KIVΛ""",
    """Cristalisia.onoken""",
    """Hydra.JamesLandinoXAkiraComplex""",
    """最高傑作.PYKAMIA""",
    """Locomotive.K""",
    """Alb.Avans""",
    """Incyde.YbeLL""",
    """彩.MisoilePunch""",
    """Poseidon.1112vsStar""",
    """WATER.A39沙包P""",
    """MiracleForestVIPMix.Rinthlive""",
    """MOBILYS.Dachs""",
    """Lyrith迷宮リリス.ユメミド""",
    """Demiurge.Rabpit""",
    """Demonkin.ForgedReigns""",
    """Re_NascencePsystyleVer.Rinth_live""",
    """Ark.kanoryo""",
    """AfterDawn.S9ryne""",
    """INFiNiTEENERZYOverdoze.RekuMochizuki""",
    """Khalid.Dolphin""",
    """QuantumHyperspace.D_AAN""",
    """FreakyUndulationsNobleKnightsofTune.JehezukielKURORAK""",
    """PANICPARADISE.DJSHIONY""",
    """ReEndofaDream.umavsモリモリあつし""",
    """心の記憶.A39沙包P""",
    """Spotlight.Ardolf""",
    """NightTheater.わかどり""",
    """Ramification.rareguyReina""",
    """DerRichter.Ωμεγα""",
    """ATHAZA.LeaF""",
]
# 曲名
SONG_NAME_LIST: list[str] = [
    """Glaciaxion""",
    """Eradication Catastrophe""",
    """Credits""",
    """Dlyrotz""",
    """Engine x Start!! (melody mix)""",
    """光""",
    """Winter ↑cube↓""",
    """Cipher : /2&//<|0""",
    """混乱-Confusion""",
    """FULi AUTO SHOOTER""",
    """HumaN""",
    """[PRAW]""",
    """Pixel Rebelz""",
    """Cereris""",
    """Non-Melodic Ragez (MUG Edit)""",
    """Sultan Rage""",
    """Class Memories""",
    """-SURREALISM-""",
    """Bonus Time""",
    """ENERGY SYNERGY MATRIX""",
    """NYA!!! (Phigros ver.)""",
    """JunXion Between Life And Death(VIP Mix)""",
    """cryout""",
    """Reimei""",
    """尊師 ～The Guru～""",
    """Spasmodic""",
    """Leave All Behind""",
    """Colorful Days♪""",
    """micro.wav""",
    """重生""",
    """NO ONE YES MAN""",
    """望影の方舟Six""",
    """Igallta""",
    """Clock Paradox""",
    """Chronologika""",
    """Nick of Time""",
    """Chronomia""",
    """Chronos Collapse - La Campanella""",
    """Rrhar\'il""",
    """Crave Wave""",
    """The Chariot ~REVIIVAL~""",
    """Luminescence""",
    """Retribution""",
    """DESTRUCTION 3,2,1""",
    """Distorted Fate""",
    """Doppelganger""",
    """もぺもぺ""",
    """MARENOL""",
    """萤火虫の怨""",
    """万吨匿名信""",
    """风屿""",
    """dB doll""",
    """Dash""",
    """云女孩""",
    """Drop It""",
    """RIPPER""",
    """Aphasia""",
    """开心病""",
    """華灯爱""",
    """Find_Me""",
    """Sein""",
    """狂喜蘭舞""",
    """Sparkle New Life""",
    """Khronostasis Katharsis""",
    """Snow Desert""",
    """Burn""",
    """Aleph-0""",
    """Next Time""",
    """Rubbish Sorting""",
    """Another Me""",
    """mechanted""",
    """life flashes before weeb eyes""",
    """Break Through The Barrier""",
    """Chronostasis""",
    """Dead Soul""",
    """Infinity Heaven""",
    """Disorder""",
    """CROSS†SOUL""",
    """Speed Up!""",
    """Magenta Potion""",
    """Get Back""",
    """Palescreen""",
    """GOODTEK""",
    """GOODBOUNCE""",
    """GOODWORLD""",
    """GOODFORTUNE""",
    """GOODRAGE""",
    """The Mountain Eater""",
    """Orthodox""",
    """End Me""",
    """Parallel Retrogression(Game Ver.)""",
    """Starduster""",
    """Electron""",
    """SIGMA""",
    """Hardcore Kwaya""",
    """Äventyr""",
    """Träne""",
    """雪降り、メリクリ""",
    """Cervelle Connexion""",
    """modulus""",
    """Wavetapper""",
    """大和撫子 -Wild Dances-""",
    """Eltaw""",
    """Initialize""",
    """桜樹街道""",
    """Get Ready!! """,
    """volcanic""",
    """Better Graphic Animation""",
    """XING""",
    """Final Step!""",
    """Cthugha""",
    """With You""",
    """Unorthodox Thoughts""",
    """Apocalyptic""",
    """游园地""",
    """energy trixxx""",
    """Nhelv""",
    """-Arkhei-""",
    """Kerberos""",
    """ρars/ey""",
    """Concvssion""",
    """ジングルベル(Jingle Bell)""",
    """Time to Night Sky (feat. Lee Yu Jin)""",
    """HAZARD""",
    """Another Me""",
    """Don\'t Never Around""",
    """RESSiSTANCE""",
    """Dreamland""",
    """Another Round""",
    """996""",
    """Future Mind""",
    """Luminescent""",
    """FULi AUTO BUSTER""",
    """I Must Say No""",
    """opia""",
    """Apocalypse""",
    """Protoflicker""",
    """Horizon Blue""",
    """You are the Miserable""",
    """Stasis""",
    """いざ、参ります""",
    """月下缭乱""",
    """On And On!!""",
    """DataErr0r""",
    """Shadow""",
    """心之所向""",
    """inferior""",
    """c.s.q.n.""",
    """Brave Notes""",
    """盏茗""",
    """青芽""",
    """Eternal Snow""",
    """Rainy Season""",
    """El Condor Pasa (Phigros Edit)""",
    """Break Over""",
    """Believe Light (feat. 果丸哒呦)""",
    """Pont des souvenirs""",
    """青丘""",
    """瓷岁""",
    """Feast远东之宴""",
    """インフェルノシティ""",
    """Upshift""",
    """Poison AND÷OR Affection""",
    """Random""",
    """零號車輛""",
    """Now Is The Time, Do It""",
    """Bougainvillea""",
    """神話""",
    """El último baile""",
    """Trojan""",
    """Temporal Shifting""",
    """Ad astra per aspera""",
    """A journey to the moonlight""",
    """Rainy Heart""",
    """Realms""",
    """ぱぴぷぴぷぴぱ""",
    """Triumph & Regret""",
    """S.A.T.E.L.L.I.T.E.""",
    """Dance with Silence""",
    """Labyrinth in Kowloon: Walled World""",
    """Compute It With Some Devilish Alcoholic Steampunk Engines""",
    """+ERABY+E CONNEC+10N""",
    """Diamond Eyes""",
    """Bitterblossom""",
    """Silence is Golden, Speech is Golden""",
    """Fractured Angel""",
    """Journey with You""",
    """Secret Illumination""",
    """Inverted World""",
    """月詠に鳴る""",
    """TECHNOPOLIS 2085""",
    """祈 -我ら神祖と共に歩む者なり-""",
    """bye""",
    """聖夜讃歌""",
    """ストレイソウル・アラウンド""",
    """Manifold Hypothesis""",
    """K.Moe (VIP)""",
    """G.V.N. (Glitter,Vomitus and Neon)""",
    """Crush BETA""",
    """Broken Sky""",
    """BRAIN HACKER""",
    """Xenolith""",
    """Artificial Existence""",
    """Indelible Scar""",
    """Antithese""",
    """PRAGMATISM -RESURRECTION-""",
    """Shine After""",
    """Bloom""",
    """幽世桔梗""",
    """千紫万紅""",
    """明鏡烈火""",
    """今天不是明天""",
    """Cuvism³""",
    """iL-Artifact""",
    """a truth seeker -Communication with Utopia will be lost-""",
    """Bounded Quietude""",
    """君往何处 (Quo Vadis)""",
    """暗夜苏醒 (REANIMATE)""",
    """Grimheart""",
    """Thrash force""",
    """Originally""",
    """黄金之城 (GOLD TOWN)""",
    """双重间谍 (Double Agent)""",
    """幻影鬼魅 (PLEASE)""",
    """Schadenfreude""",
    """Le temps perdu""",
    """Fixations Toward the Stars""",
    """valor/starcross""",
    """Comet""",
    """白と黒のバケモノ""",
    """Devotion""",
    """Kirakira Noel Story!!""",
    """Shelter""",
    """蝎虎天体 -Lacertid-""",
    """贝多芬祝福 (Beethoven Blessing)""",
    """インマイマインド""",
    """ニライカナイ (NiraicA_nai Mix)""",
    """Swing Skip Drop""",
    """宇宙残骸少女 (Cosmic Dusty Girl)""",
    """Resolver""",
    """Luminous Entities Lost Heart""",
    """KIZUNA Resolution""",
    """AbsoluTe disoRdeR""",
    """Aphrodite\'s Child (short ver.)""",
    """DevIAtiOn (short ver.)""",
    """NO x""",
    """Alice in a xxxxxxxx""",
    """Radiance""",
    """Diamond Dust""",
    """Stardust:RAY""",
    """Frozen Heart""",
    """Helios""",
    """Flutter Echo""",
    """Re：birth""",
    """Avataar ~Reincarnation of Kalpa~""",
    """雪降り ~雪が降っている~""",
    """Retribution ~ Cycle of Redemption ~ """,
    """アンビバレンス""",
    """Komplexe""",
    """sølips""",
    """QZKago Requiem""",
    """So laggy! (feat. Uzumaki)""",
    """000 -Ain Soph Aur-""",
    """Xep+ion""",
    """Archidoxen""",
    """百鬼֎夜行""",
    """BANGING STRIKE""",
    """The Whole Rest""",
    """Cristalisia""",
    """Hydra""",
    """最高傑作""",
    """Locomotive""",
    """Alb""",
    """Incyde""",
    """彩""",
    """Ποσειδών""",
    """WATER""",
    """Miracle Forest (VIP Mix)""",
    """MOBILYS""",
    """Lyrith -迷宮リリス-""",
    """Demiurge""",
    """Demonkin""",
    """Re_Nascence (Psystyle Ver.) """,
    """Ark""",
    """After Dawn""",
    """INFiNiTE ENERZY -Overdoze-""",
    """Khalid""",
    """Quantum Hyperspace""",
    """Freaky Undulations ~Noble Knights of Tune~""",
    """PANIC PARADISE""",
    """Re：End of a Dream""",
    """心の記憶""",
    """Spotlight""",
    """NightTheater""",
    """Ramification""",
    """Der Richter""",
    """ATHAZA""",
]
# 曲师
COMPOSER_LIST: list[str] = [
    """SunsetRay""",
    """NceS""",
    """Frums""",
    """Likey""",
    """CrossingSound""",
    """姜米條""",
    """Ctymax feat. NceS""",
    """Tetrajectory feat. Ctymax""",
    """Only My Black Score""",
    """MYUKKE.""",
    """SOTUI""",
    """Bluewind""",
    """Normal1zer""",
    """SunsetRay/NceS""",
    """Normal1zer""",
    """MonstDeath""",
    """Antistar feat. Ctymax""",
    """Itsuki""",
    """Megalo_PaleWhite""",
    """Tanchiky""",
    """FLuoRiTe/姜米條""",
    """1N6Fs""",
    """Ju_E""",
    """影虎。""",
    """rider""",
    """姜米條☆颶風 ~ ♫元力上人♫""",
    """rider""",
    """P4koo feat. つゆり花鈴""",
    """dandeless""",
    """姜米條""",
    """MYUKKE.""",
    """Se-U-Ra""",
    """Se-U-Ra""",
    """WyvernP""",
    """Hundotte""",
    """P4koo""",
    """Lime""",
    """SunsetRay""",
    """Team Grimoire""",
    """LandRoot""",
    """Attoclef""",
    """米虾Fomiki & 初云CLoudie""",
    """nm-y & Kry.exe""",
    """Normal1zer vs. Broken Nerdz""",
    """Sakuzyo""",
    """LeaF""",
    """LeaF""",
    """LeaF""",
    """闫东炜""",
    """闫东炜""",
    """闫东炜""",
    """YUE.STEVEN/uen""",
    """小红Akane，李祥晖""",
    """符白牙/SiYFics""",
    """Asuka""",
    """Friedwav""",
    """闫东炜""",
    """闫东炜""",
    """闫东炜""",
    """K-forest""",
    """朔(Apo11o program vs. お月さま交響曲) ft. kuroa*×荒巻""",
    """LeaF""",
    """rider""",
    """Halv""",
    """WyvernP""",
    """NceS""",
    """LeaF""",
    """SaMZIng""",
    """Ctymax vs. NceS""",
    """Neutral Moon""",
    """rareguy""",
    """BilliumMoto""",
    """lixound""",
    """黒皇帝""",
    """Sound Souler""",
    """HyuN""",
    """HyuN feat. YURI""",
    """HyuN feat. Syepias""",
    """DarTokki""",
    """EmoCo.""",
    """CAP3""",
    """WyvernP feat. Madol""",
    """EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """Paul Bazooka""",
    """tokiwa""",
    """ZxNX as \"Delaina\"""",
    """Tetrajectory""",
    """Quree""",
    """ElousΛ.-FZ""",
    """Kry.exe""",
    """EnFr""",
    """Grand Thaw / Rigël Theatre""",
    """MALVA.""",
    """A-39""",
    """SCTL""",
    """PTB10""",
    """Frums""",
    """adaptor vs DRIVE.""",
    """Fl00t""",
    """iF""",
    """kozato snow""",
    """iF""",
    """DETRO a.k.a. ルゼ""",
    """ルゼ""",
    """ginkiha""",
    """Lime""",
    """USAO""",
    """Cashew""",
    """Joulez""",
    """Z ClaxX & SumaiLight""",
    """椒盐菠萝""",
    """KAH""",
    """Silentroom""",
    """Sera Amagi""",
    """Zris""",
    """siqlo""",
    """Halv""",
    """A-39/沙包P""",
    """HyuN & KLYDIX""",
    """Limpid""",
    """D_AAN""",
    """HAMA""",
    """ぐるたみん""",
    """z1on & kyrrin""",
    """Justin Dai""",
    """李化禹""",
    """Ray Nautica & Reku Mochizuki""",
    """Daison""",
    """MYUKKE.""",
    """TangJuan""",
    """rN""",
    """アリスシャッハと魔法の楽団""",
    """Silentroom""",
    """Nothing But Requiem feat. Aikapin & Chiyoko""",
    """t+pazolite""",
    """Maozon""",
    """U-ske feat. 棗いつき""",
    """月見静華 vs. LUNARiUM""",
    """ETIA. feat. Jenga""",
    """Cosmograph""",
    """姜米條&SumaiLight""",
    """姜米條""",
    """姜米條""",
    """Aoi""",
    """Turquoise(DRIVE.+Nota)""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """Abyss Idols""",
    """Abyss Idols""",
    """Plastic Fruits""",
    """K-forest""",
    """Scaler & Mestie & 果丸哒呦""",
    """VeetaCrush vs. [itsu(feat.itsu)]""",
    """BLACK 0""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """Ponchi♪ feat. はぁち""",
    """Iriss-Frantzz""",
    """LeaF""",
    """Sobrem × Silentroom""",
    """seatrus""",
    """Roy Mikelate""",
    """Jade""",
    """Pica & M2U""",
    """Θ""",
    """litmus*""",
    """Lure Rabbit & V!C""",
    """Rabbit House""",
    """Yesod""",
    """BelieverInYou(阿卡姆巫师)""",
    """Hinkik & A Himitsu""",
    """ころねぽち With 立秋""",
    """typeMARS""",
    """かめりあ""",
    """かめりあ""",
    """かめりあ""",
    """かめりあ""",
    """かめりあ""",
    """SYNTHETIC""",
    """imvi""",
    """NIWASHI""",
    """DJ Raisei""",
    """Iris""",
    """Yooh""",
    """ARForest""",
    """Feryquitous feat.藍月なくる""",
    """PRASTIK DANCEFLOOR""",
    """光吉猛修 VS 穴山大輔 VS Kai VS 水野健治 VS 大国奏音""",
    """DingerBox""",
    """A-39/沙包P""",
    """みーに""",
    """cybermiso feat. tigerlily""",
    """ZxNX""",
    """Salty Salt & Unfold33""",
    """shadow_bling""",
    """Jungo & MAX 3 feat. 刘佳宜Snow & 幻影刃shadow""",
    """SOMON""",
    """Tatsh""",
    """Jun Kuroda""",
    """Noah""",
    """Blacklolita""",
    """Laur""",
    """ADean & JocularACE""",
    """targ & 麻团qwq""",
    """Capchii feat. まるもこ""",
    """r0y vs. WABI""",
    """M-UE vs. Reku Mochizuki""",
    """PIKASONIC feat. 兰音Reine""",
    """Fl00t vs Halv""",
    """Link\'\'0""",
    """kuro""",
    """Finite Limit vs SiLiS""",
    """M2U""",
    """Warak""",
    """Puru""",
    """KAH vs. E0ri4""",
    """SNKS & Mizku""",
    """MEMME""",
    """Wav.AV""",
    """R300K""",
    """ZxNX""",
    """Daison""",
    """Foodbot""",
    """Lundy vs. Wyvren""",
    """CNHKSS feat. 符白牙""",
    """テヅカ""",
    """Connexio""",
    """Reku Mochizuki""",
    """MeatyRabbit & NceS""",
    """Cream vs. Daily天利""",
    """Nauts""",
    """レシオP""",
    """roop from STR""",
    """ミハイル""",
    """辻原一郎""",
    """Gomadare""",
    """NormalM feat. Usagi Denki""",
    """TAG""",
    """Acute Disarray""",
    """RUQOA""",
    """polysha""",
    """Juggernaut.""",
    """Nagiha""",
    """Nhato""",
    """Masahiro “Godspeed” Aoki""",
    """kanone vs. BlackY""",
    """A-39 / 沙包P""",
    """NOA(Cortrix) & BotaNya""",
    """Cansol""",
    """ああああ""",
    """Scarlette a.k.a CrYmson""",
    """AiSS w/ 夜輪 ft. 結月ゆかり""",
    """Ardolf vs. Daily天利""",
    """すりぃ×相沢""",
    """雄之助 feat. Sennzai""",
    """rintaro soma""",
    """t+pazolite""",
    """ShrimpCats. (はぁち×後藤涼輔)""",
    """Yumeji""",
    """Acotto""",
    """Se_IRA""",
    """Salad Savior""",
    """Dew Pleiades""",
    """KIVΛ""",
    """onoken""",
    """James Landino X Akira Complex""",
    """PYKAMIA""",
    """♠K""",
    """Avans""",
    """YbeLL""",
    """MisoilePunch♪""",
    """1112 vs. Star＊""",
    """A-39/沙包P""",
    """Rinth_live""",
    """Dachs""",
    """ユメミド""",
    """Rabpit""",
    """Forged Reigns""",
    """Rinth_live""",
    """kanoryo""",
    """S9ryne""",
    """Reku Mochizuki""",
    """Dolphin""",
    """D_AAN""",
    """Jehezukiel + KURORAK""",
    """DJ SHION.Y""",
    """uma vs. モリモリあつし""",
    """A-39/沙包P""",
    """Ardolf""",
    """わかどり""",
    """rareguy & Reina""",
    """Ωμεγα""",
    """LeaF""",
]
# 画师
DRAWER_NAME_LIST: list[str] = [
    """艾若拉""",
    """海产""",
    """Ctymax""",
    """DoublePian""",
    """赤芽""",
    """winder""",
    """翠冷兮""",
    """IvyTowers""",
    """L-sp4""",
    """ViscerA & Psycholine""",
    """CH""",
    """老张""",
    """艾是Abby""",
    """IvyTowers""",
    """cycats""",
    """笔记RE""",
    """xperz""",
    """喵n葵""",
    """笔记RE""",
    """Karameru""",
    """NEKO&海产""",
    """IvyTowers""",
    """Haight""",
    """英英英""",
    """1B""",
    """昔璃☆暴雨 ~ ♫危難聖帝♫""",
    """笔记RE""",
    """Doro-nyong & Ratif""",
    """snake.ribs""",
    """昔璃&TNiK""",
    """青鸟""",
    """鲸弑""",
    """Se-U-Ra""",
    """汉堡""",
    """幽灵星""",
    """青鸟""",
    """inukoro""",
    """老张""",
    """犀牛坨动画工坊""",
    """笔记RE""",
    """翠冷兮""",
    """子狼""",
    """NerSAN""",
    """rN""",
    """knife美工刀""",
    """海产""",
    """cycat""",
    """喵n葵""",
    """L-sp4""",
    """IvyTowers""",
    """cycats""",
    """何呵""",
    """艾是Abby""",
    """御坂果子""",
    """TNiK""",
    """何呵""",
    """笔记RE""",
    """昔璃""",
    """IvyTowers""",
    """YuKiMuMa""",
    """hideo""",
    """DoublePian""",
    """1B""",
    """utosao""",
    """knife美工刀""",
    """knife美工刀""",
    """Optie""",
    """叶藤""",
    """knife美工刀""",
    """IvyTowers""",
    """IvyTowers""",
    """百九十八""",
    """Xquid""",
    """Sand""",
    """Photonskyto""",
    """DoublePian""",
    """Nabom""",
    """knife美工刀""",
    """TNiK""",
    """NOISER""",
    """TNiK""",
    """GAMEBAKA""",
    """Ctymax feat. EBIMAYO""",
    """EBIMAYO""",
    """EBIMAYO""",
    """Ctymax""",
    """Ctymax feat. EBIMAYO""",
    """START SEED""",
    """cycats""",
    """何呵""",
    """青鸟""",
    """IvyTowers""",
    """DoublePian""",
    """塔塔""",
    """EnFr""",
    """Grand Thaw / Rigël Theatre""",
    """しえろ""",
    """犀牛坨动画工坊""",
    """SCTL""",
    """geralt""",
    """百九十八""",
    """りゅうら""",
    """xperz""",
    """あおお/A-ZERO, morph""",
    """あおお/A-ZERO, morph""",
    """あおお/A-ZERO, morph""",
    """あおお/A-ZERO, morph""",
    """A-Zero Project""",
    """打雷打人（青鸟 modified）""",
    """谷地（青鸟 modified）""",
    """谷地（青鸟 modified）""",
    """ADZUKI""",
    """ASXX""",
    """佑木いずみ & Ctymax""",
    """CEM""",
    """手鞠鈴 & 自動車 原付""",
    """駿""",
    """Hachimitsu☆Boy""",
    """Eridani""",
    """出前 x nekomiya""",
    """汉堡""",
    """爱39的Konya""",
    """ZG""",
    """ZG""",
    """ZG""",
    """Arahosi""",
    """LINUS""",
    """海产""",
    """艾是Abby""",
    """笔记RE""",
    """Keiby.comics""",
    """鲸弑""",
    """cycats""",
    """cycats""",
    """rN @ 湯元画伯""",
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """Lanota © Noxy Games Inc. """,
    """緑風マルト""",
    """TNiK""",
    """わっふゑ""",
    """Photonskyto""",
    """御坂果子""",
    """笔记RE""",
    """群青kurara""",
    """Ctymax vs. TNiK feat. 出前""",
    """林语""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """Sak""",
    """Robin""",
    """青鸟""",
    """圆规compasses""",
    """圆规compasses""",
    """林语""",
    """BLACK 0""",
    """茶鸣拾贰律""",
    """茶鸣拾贰律""",
    """LESYEF & 藍瀬 まなみ""",
    """Iriss=Frantzz=s-don""",
    """笔记RE/海产""",
    """Harkiadel""",
    """2AI4wU4""",
    """青鸟""",
    """TNiK""",
    """mology (青鸟&V17AMax Modified)""",
    """mology (青鸟&V17AMax Modified)""",
    """Lapelristar (青鸟&V17AMax Modified)""",
    """mology (青鸟&V17AMax Modified)""",
    """Lyrebird Ferdinant (青鸟&V17AMax Modified)""",
    """汉堡""",
    """Sodhelium""",
    """圆规compasses""",
    """上倉エク""",
    """何呵""",
    """青鸟""",
    """林语""",
    """鲸弑""",
    """山崎团""",
    """猫箱Catbox feat. 祈莲""",
    """彗星 feat. 祈莲""",
    """鲸弑""",
    """Jerry & OsuMe65""",
    """OsuMe65""",
    """BTKCyber (青鸟 modified)""",
    """Juice Black (青鸟 modified)""",
    """Mechari (青鸟 modified)""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """海产""",
    """绀屋""",
    """伊恩 (青鸟 modified)""",
    """阿清 (青鸟 modified)""",
    """BTKCyber (青鸟 modified)""",
    """祈莲""",
    """笔记RE""",
    """午苔veeee~""",
    """SOMON""",
    """2AI4wU4""",
    """2AI4wU4""",
    """兜""",
    """釜飯轟々丸 + jht (Design: 祈莲)""",
    """シエラ (Design: 祈莲)""",
    """海里狄七 feat. 存艺""",
    """注射""",
    """瀬名""",
    """中本ひょうり""",
    """中本ひょうり""",
    """KiTA & 一击即溃""",
    """sikkari""",
    """Fl00t""",
    """rokopon""",
    """Hiro vs Zeth""",
    """LRAY (青鸟 modified)""",
    """MHK (青鸟 modified)""",
    """临时工 & 倪尔""",
    """自動車 原付 vs. GAMEBAKA""",
    """Keiby.comics""",
    """RM Design Team (青鸟 modified)""",
    """RM Design Team (青鸟 modified)""",
    """RM Design Team (青鸟 modified)""",
    """验光蒸鱼""",
    """子狼""",
    """AriaL [edited by Stelli]""",
    """AriaL & 57_dayo [edited by Stelli]""",
    """小黄鸡叽叽叽叽叽叽修复中""",
    """久世""",
    """Shimoruchiko""",
    """ナナシ""",
    """诡异童话""",
    """白 & 小鹏xpeng""",
    """RM Design Team (青鸟 modified)""",
    """すずか爆弾""",
    """3z""",
    """ディン""",
    """TOTOTO """,
    """Transendium""",
    """Transendium""",
    """Transendium""",
    """Kyuare & Wsx""",
    """cala for Immaculée Sekai""",
    """cala for Immaculée Sekai""",
    """cala for Immaculée Sekai""",
    """神居冰绘 feat. 祈莲""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """SEGA (V17AMax modified)""",
    """山山奇""",
    """Spectro""",
    """Taurell""",
    """QueseraGames Co., Ltd.""",
    """QueseraGames Co., Ltd.""",
    """Vios.NoFurry.git""",
    """死と花の大祭司(ʌᴉoƨმᴉϝ);;""",
    """SEGA (祈莲 modified)""",
    """SEGA (祈莲 modified)""",
    """SEGA (祈莲 modified)""",
    """SEGA (祈莲 modified)""",
    """塩焼とまと""",
    """NerSAN""",
    """クルス (Ctymax modified)""",
    """n/a (Ctymax modified)""",
    """軽目くお (Ctymax modified)""",
    """Rutumn feat. 汉堡""",
    """©2025 Rayark Inc. CYTUS II®""",
    """©2025 Rayark Inc. CYTUS II®""",
    """©2025 Rayark Inc. CYTUS II®""",
    """Nai Guozi""",
    """Otaku_宅""",
    """©2026 Rayark Inc. CYTUS II®""",
    """©2026 Rayark Inc. CYTUS II®""",
    """©2026 Rayark Inc. CYTUS II®""",
    """老张""",
    """knife美工刀""",
    """L-sp4""",
    """わっふゑ""",
    """何呵""",
    """青鸟""",
    """Jeffery""",
    """Tsuioku""",
    """MOAI WORKS""",
    """月亮酱""",
    """knife美工刀""",
    """HAZUQU""",
    """sa1t""",
    """PEZZ feat. 祈莲 & CattoHato""",
    """百九十八""",
    """masiro vs. adaptor""",
    """爱39的Konya""",
    """NerSAN""",
    """青鸟""",
    """cokeAnut""",
    """森灵""",
    """御坂果子""",
]
# 谱师
CHARTER_LIST: list[str] = [
    """Barbarianerman""",
    """迟戈 vs. Likey""",
    """Concat(Ramification,Richter)""",
    """Ner ~ See you next time ~""",
    """Uvernight fixed by 百九十八""",
    """_鉄""",
    """Likey -For an old friend-""",
    """StupiGGy vs. 百九十八 ft. 野从""",
    """Salt & Uvernight""",
    """Uvernight""",
    """-JKy-""",
    """Magazet""",
    """_鉄 (Isotope 59)""",
    """B.B.M.""",
    """阿爽 fixed by Clutter""",
    """野从菠萝""",
    """TimiTini & HaraKuma""",
    """Phigros Charting Team""",
    """Eaimo vs. CtyNer dancing wildly""",
    """Pcat【零】198""",
    """RTH""",
    """RWND -p 16493:62786:92551""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by 野从&晨""",
    """Timi今天吃神马""",
    """BlindForest 『Observing』""",
    """Ctymax vs. 阿爽""",
    """百九十八""",
    """Ctymatch Girl""",
    """晨""",
    """上班睡大觉_Sleepyhead""",
    """\'\'-1\'\'""",
    """while(TangScend==TangScend);""",
    """COLORFUL CTYMAX""",
    """198 in Kowloon""",
    """Barbarianerman vs. Snorkel""",
    """Rikko EXPERT Lv.40""",
    """Likey & Gausbon""",
    """村头村头 CTY Story!!""",
    """Rikko EXPERT Life:999""",
    """{Devastation,Destruction}""",
    """jouR.ney with hold""",
    """s.t.p.g.""",
    """対流に巻き込まれ""",
    """StupiGGy vs. 阿爽""",
    """StuRmwind""",
    """∅""",
    """Catcats & 百九十八""",
    """RDRT -p 20:02:21""",
    """Clutter & Barbarianerman""",
    """ParParianerman""",
    """OPCII_0584_X""",
    """4731474142592B45""",
    """jeitie gets sent to the sun""",
    """其一 呼吸尚存的标志""",
    """Pat Brick Man Mr.C & Mr.B""",
    """XMT小咩兔 vs. 上班睡大觉_Sleepyhead""",
    """フィグロス譜面チーム \"Rikko feat. Ner\" -Pray for \"PHI\"-""",
    """Ctymax vs. 阿爽  fixed by B B M pow""",
    """SeveredEntity (BlindForest vs. rN) feat. Δ""",
    """-StupiGGy- fixed by 晨""",
    """分化者 fixed by Barbarianerman""",
    """StupiGGy -The Origin-""",
    """totally ramified COC""",
    """Barbarianerman & J.R""",
    """IMD_6""",
    """断罪の剣『神』""",
    """XMT wishing upon a satellite""",
    """爽夜讃歌""",
    """Barianic Baradise""",
    """R:kko (IMD)""",
    """Salt""",
    """百九十八 vs. Barbarianerman""",
    """零號宇夜""",
    """ネルサン (I make charts slowly)""",
    """Two skunks (Ctymax and 晨) in Africa shouting WAHHHHHH!""",
    """Ner, the inferior""",
    """TECHNOXMT vs. LATENCYPOLIS""",
    """Salt feat. XMT小咩兔""",
    """上班摸大鱼 a.k.a. 海洋咩兔""",
    """Clutter is coppery，Tumult is coppery""",
    """StuRmfeuer""",
    """Warning: XMT is infected by Trojan!!""",
    """Gausbon""",
    """-Seek A Lnside Truth-""",
    """急流に巻き込まれ""",
    """無†極""",
    """Likey & 198ar""",
    """Hook vs. _鉄""",
    """inert COC""",
    """Divination Fortune""",
    """M3d1uM & 百九十八""",
    """B.""",
    """XMT & 198""",
    """Pat Brick Man Mr.N feat. Ner of Time""",
    """Barbarianerman, Overture before the story""",
    """L.I.K.E.Y.""",
    """XMT & Salt""",
    """Executor-X""",
    """1÷98""",
    """穿山甲-1""",
    """RipHall vs. Likey""",
    """NerSAN vs. 阿爽 『Collapse』""",
    """Salt feat. M3ow""",
    """Monorail""",
    """H.C.C. fixed by Barbarinerman""",
    """晨_鉄""",
    """4D45474142592B45""",
    """□MT in a XXXXXXXX""",
    """Hara is golden, Kuma is golden""",
    """Ner ~Freaky Cat of Charting~""",
    """Gausbon vs. XMT小咩兔""",
    """JKy as \"Stray Cat\"""",
    """無彩色""",
    """Rft.""",
    """Ctymax""",
    """Pcat & 百九十八""",
    """Cty moyules""",
    """右果_Ary""",
    """Gausbon & StupiGGy""",
    """Debut under spotlights!< Simon_Axis""",
    """Ary""",
    """Find_Ctymax fixed by 百九十八""",
    """Su1fuRikko""",
    """Pcat""",
    """Bariantum Hyperianerman""",
    """人外侵略地球计划""",
    """Ctymax but 5 years later""",
    """Likey""",
    """完璧 × 北星""",
    """Alloces""",
    """Su1fuR -FAISEURS DE PANIQUE-""",
    """NerSANTA & Gausbell""",
    """亚树见希子 & 百九十八""",
    """Su1fuR""",
    """森德雷斯 vs. 百九十八""",
    """猫の信 & 百九十八""",
    """AUTO. SHOOTER. fixed by Ctymax""",
    """撕裂者『無極』 fixed by 晨""",
    """Sillyp vs. 阿爽""",
    """Merry xmAS""",
    """Brave Eaimo""",
    """IUIsauce""",
    """dancing\"L\"ine 2085""",
    """Another cat""",
    """Hardcore Barbaya""",
    """鲲&百九十八""",
    """Sillyp & Alloces""",
    """Sempiternal Fxxxxxx Resolution!""",
    """Snorkel""",
    """Jeitie""",
    """A.S.H""",
    """阿爽""",
    """CTYMAX ????""",
    """C.Max (PBM)""",
    """Barbarvillea""",
    """Salt & _鉄 inspired by 存在証明 [X]""",
    """LonelyKnight""",
    """ø""",
    """Bσrbσriσn∑rmσn.∑x∑""",
    """実戦 with Rikko""",
    """Min(C,t,y)""",
    """StR-9""",
    """Deep Dark Ctymax""",
    """弧光""",
    """阿爽 vs. Ctymax -Haose 垃圾-""",
    """CorruptedEntity & 野从""",
    """Another Stage""",
    """光る星""",
    """Ctymax vs. 晨""",
    """Magazet wanders within StR-1""",
    """Another M3""",
    """Ctymax in a volcano, very delicious""",
    """TangScend""",
    """Gausbon ~ See you next time ~ """,
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by Pcat""",
    """百九十八 feat. Likey""",
    """jeitie touches grass""",
    """Eaimo fixed by NerSAN""",
    """雑""",
    """BarbariaNerSAN feat. Snorkel""",
    """头鱼头鱼 MAX Story!!""",
    """鲲 fixed by 百九十八""",
    """小咩兔、参上""",
    """Bσrbσriσnermσn.exe""",
    """while(TangScend<=TangScend);""",
    """KillJoy""",
    """Ctymax vs. Gausbounce""",
    """Simon_Axis vs. Su1fuR""",
    """OPENING/Level R""",
    """XMT小咩兔 vs. Barbarianerman""",
    """J.R""",
    """JKy, the inferior""",
    """兔咩小 VS 咩小兔 VS 小兔咩 VS 咩兔小 VS 兔小咩""",
    """[!!12:l<l<ο!!]""",
    """～Algax vs. RipHall～""",
    """NerSANN""",
    """Pat Brick Man Mr.C""",
    """Sparkle Ctymax""",
    """NerSANTA vs. BarbarianerSLEDGE""",
    """-""",
    """完璧 vs. 癒株 -Autumn Memory-""",
    """NerSAN & 百九十八""",
    """StupiGGy -The Startline-""",
    """Raiky Season""",
    """Ner & 198 from 「PHIGROS MOON」""",
    """N-23""",
    """adky""",
    """Jαckψ feat. Βαρβαροςαντρας""",
    """奇跡の希 feat. 奇跡の従""",
    """iv""",
    """Merry ChristymAxS""",
    """Rikko from「PHIGROS MOON」""",
    """Gausbon vs. 阿爽""",
    """JKy vs StrayCat""",
    """阿♪爽""",
    """六回目Traveler Scend""",
    """阿爽『Destroy』""",
    """NerSANNN""",
    """ƃuɐnɥs∀ .sʌ uoqsnɐ⅁""",
    """Su1fuR vs. Simon_Axis""",
    """Ner as \"SPΔDE\"""",
    """Barbarianerman vs. HaraKuma""",
    """with U""",
    """奇跡の希""",
    """爬爬""",
    """Believe Ctymax & TimiTini""",
    """～漂泊者～凹酱""",
    """Ner＜Jazz for your soul .)""",
    """Helabot""",
    """IMD_0b0110""",
    """XMT, Encore after the end""",
    """凛""",
    """JKy""",
    """XMT after BarbarNerSAN""",
    """Barbarianerman, Main theme within the somnium""",
    """啊0哒0咔0哟 & Dilated""",
    """Hara小兔组""",
    """Blessing beyond myself.""",
    """Swing Salt ♪""",
    """b.b.n.m.""",
    """Barbarianerman feat. 晨""",
    """Creator ~ StupiGGy""",
    """A.S.H.""",
    """N.E.R.1.9.8.""",
    """Skuwo""",
    """Max(C,t,y)""",
    """Simon_Axis""",
    """Barbarianerman vs. Alloces""",
    """さるふるふるさ""",
    """StR-1 watches Ctyfilm""",
    """-NerSAN & Su1fuR-""",
    """Arenn Salty feat. LDA""",
    """StR-1""",
    """騎士 vs. Knight """,
    """縱連打の信者☆無極""",
    """夜明の剣『靈』""",
    """阿爽 eat Ctymax""",
    """Passport:Constructor""",
    """Rikko³ [Normal]""",
    """Clutter BETA""",
    """Uvernight & Su1fuR""",
    """完璧 [WARNING: DRAG OVERLOAD]""",
    """A.S.H&晨""",
    """其三 我所存在的证明""",
    """N\\erry Xmas""",
    """Likey affected by Ancestral Xhronicle""",
    """StupiGGy""",
    """Jαckψ a.k.a JKy""",
    """逆天使の悪魔 【Likey】""",
    """professional Rikko""",
    """Absolute(6)""",
    """RXhuang""",
    """WhiteCat.""",
    """曦枢 vs. 鎏光 -Lv.70 LEAF-""",
    """BLACK CTYMAX""",
    """倪之所爽""",
    """奥術 ~The Empery~""",
    """RDRT -p 20:08:31""",
    """COLORFUL BLACK GAUSBON""",
    """Salt & Barbarianerman""",
    """CN_115+TangScend""",
    """逆流而上的小咩兔""",
    """|R|I|K|K|O| NORMAL""",
    """SPΔDE & 倪尔qwq""",
    """while(TangScend>=TangScend);""",
    """StR-1 & 右果_Ary""",
    """Passport:Visitor""",
    """vacant/stupiggy""",
    """無極☆雷鳴 ~ ♫死の序曲♫""",
    """Bear""",
    """reanimate_6k_nm.imd""",
    """Яadiance""",
    """P & U""",
    """Likey underground""",
    """StrayCat""",
    """弧光 With Opposition""",
    """Likey & 百九十八""",
    """Barbarianerman & Regret""",
    """Rikko & TangScend""",
    """Clutter Echo""",
    """Gausbounce""",
    """云正太""",
    """Cloud Catcats""",
    """Ctymax respect for STAR TRACK in 2008""",
    """Drop Catcats""",
    """Nr3_Official""",
    """HaraKuma""",
    """NerSAN feat. Takanashi Rikko""",
    """TimiTini →\"X\"← 阿爽""",
    """魔王、大咩兔の兄 『大咩免』!!""",
    """SimonAxis""",
    """Nothing But Likey""",
    """時の希 & 百九十八""",
    """Jeitie & CorruptedEntity 『Hollow』""",
    """NerSAN vs. 阿爽""",
    """h.o.m.e.e.e.""",
    """NerSAN""",
    """白""",
    """merry CNrisTimas""",
    """Barbarialid""",
    """杂波不是杂啵，野从不是野丛""",
    """Burn Full Catcats vs. Ctymatch Girl""",
    """M3d1uM""",
    """壹號阿爽""",
    """Knight""",
    """N\\erry Xmas 2024""",
    """生根发芽的小咩兔""",
    """Simon_Axis >< Likey""",
    """J0(_)I2|\\|3y\'5 3|\\||)""",
    """merry XM AS""",
    """Arenn Saki as \"myStery\"""",
    """Lumiere""",
    """monochrome ILLUSION""",
    """無†極 fixed by Rikko""",
    """Pcat『Scatter』""",
    """{Demolition,Devastation,Destruction}""",
    """Barbarianerman vs. NerSAN""",
    """Cluttler with ShelteR""",
    """平川の剣『士』""",
    """Sillyp vs. 晨""",
    """BarbariaNERman vs. JKy""",
    """Δ (M3d1uM vs. Salt)""",
    """Spy-Simon_Axis | Spy-騎士""",
    """VikingNexus""",
    """撕裂者『Alloces vs. Shin』""",
    """クラッタ・アナザー・ラウンド""",
    """Doubt Ful""",
    """B.A.R.B.A.R.I.A.N.E.R.M.A.N.""",
    """{Destruction}""",
    """Catcats & 百九十八 fixed by Clutter""",
    """Simon_Axis vs. Likey [Respect Ner as \"SP∆DE\"]""",
    """jouR.ney to the end【COVERED】""",
    """Burn Full Catcats""",
    """Eastern Ailuropoda Gang""",
    """Su1fuRikko × rN \"judgemeNt fRom the cataStRophy\"""",
    """晨 vs. 阿爽""",
    """XMT as \"eX-MentalisT\"""",
    """不喜欢键的COC""",
    """NerSAN feat. Pcat""",
    """Motorcoach""",
    """St2.1GHz -Før The Pigeons-""",
    """RDRT -p 19:08:31""",
    """1uminous StaR""",
    """【梦之起始】爬爬 vs. 盐""",
    """百九十八 busting 阿爽""",
    """Su1fuR、快斬！""",
    """¯EASY""",
    """Apocalyptic Dissonance""",
    """THE LAST 198""",
    """Clutter""",
    """StaR-1""",
    """Arenn Saki vs. NerSAN""",
    """Uvernight fixed by StR-1""",
    """We are the Miserable""",
    """六回目Traveler Scend as \"Knight of Arq\"""",
    """Alloces feat. Uvernight""",
    """波之所杂""",
    """Jαckψ""",
    """LuminousGausbon""",
    """椒盐倪尔""",
    """Ctymax vs. IUIsauce -村头烤鱼蘸凹酱-""",
    """Manufacturer ~ Rikko""",
    """COC  feat. Su1fuR""",
    """while(TangScend=TangScend);""",
    """晨 vs. Ctymax""",
    """jeitie goes outside""",
    """Latency, Finale of the dream""",
    """Demiurge ~ Dawn""",
    """Gausbounce & 晨""",
    """COC""",
    """小咩兔的多指课堂 vs. 上课睡大觉""",
    """4B314C3042592B45""",
    """ST AS is XMT""",
    """_鉄咩兔""",
    """NerSAN vs. Ctymax as \"泥头鱼\"""",
    """Likey & Barbarianerman""",
    """One skunk (Ctymax) in Africa""",
    """Barbarianerman fixed by Clutter""",
    """HD R.esolution""",
    """Nothing But Ner & Pcat""",
    """Uvernight from CYTUS II""",
    """野从""",
    """空の希""",
    """Barbarianerman feat. Gausbon""",
    """Rikko & 198""",
    """Xlutter guided by three Oaths""",
    """Believe TimiTini""",
    """XMT小咩兔 & Myna""",
    """Ctymax drives in BlindForest""",
    """Ctymax vs. 百九十八""",
    """HCC!!!""",
    """Rikko""",
    """信仰の剣『生』""",
    """Future BarbarXMT""",
    """『兔』年大吉""",
    """Gausbon feat. 迟戈&野从""",
    """Barbarianerman vs. Uvernight""",
    """Likey feat. 198""",
    """StupiGGy fixed by 百九十八""",
    """CN_115 as \"prediCameNt\"""",
    """不喜欢线的COC""",
    """thrAsh forSe""",
    """imd visual charter \"Rikko\" since 2014""",
    """De Fiance""",
    """孤独な騎士 Against 魔王、大咩兔""",
    """TangScend -Err0rederci-""",
    """Myna feat.Sleepyhead""",
    """R/kko""",
    """Catcats a.k.a. 無極 vs. H.C.C. fixed by 晨""",
    """扫佛不是嫂夫""",
    """鲲""",
    """Minibus""",
    """Find_Ctymax""",
    """Gausbon fixed by XMT""",
    """Barbarianerman.exe""",
    """波""",
    """Gino""",
    """Sparkle Ctymax fixed by 百九十八""",
    """BlindForest""",
    """[该用户已被禁言]""",
    """『流』年大顺""",
    """阿爽 & 百九十八""",
    """<= Noblesse Jeitie =>""",
    """Su1fuR -All about YOU & ME-""",
    """XMT小咩兔""",
    """ARE YOU JEITIE!!!""",
    """ANGER&SORROW >^< LDA""",
    """Nothing But Uvernight""",
    """vesper/straycat""",
    """Crush βETA""",
    """乱流に巻き込まれ""",
    """Where are Ctymax and 阿爽?""",
    """Ctymax after 7 years""",
    """SantR""",
    """&ikko""",
    """LDAJOY&PLEASANT ^V^ LDA""",
    """Passport:Governor""",
    """阿爽 fixed by Barbarianerman""",
    """NerSAN sipping XMTea""",
    """Su1fuRikko \"SouRce of the metaveRse\"""",
    """Snorkel vs. NerSAN""",
    """Clutter vs. Salt""",
    """unDefined Future""",
    """Likey """,
    """阿爽 fixed by Barbarinerman""",
    """R.""",
    """Barbarianerman & NerSAN in the ICU""",
    """Arenn Saki vs. Catcats vs. 百九十八""",
    """TimiTini""",
    """ɹǝʇʇnlƆ""",
    """Likey >IT\'S SHOWTIME!""",
    """Ctymax vs. Barbarianerman""",
    """晨 vs. XMT小咩兔""",
    """2B45524142592B45""",
    """Stray Cat Around""",
    """Sillyp""",
    """其二 向前迈进的理由""",
    """Arenn Saki as \"lAβyrinS\"""",
    """百九十八 feat. NerSAN""",
    """啊哒咔哟 & 小咩兔 & COC""",
    """Believe Ctymax""",
    """Affection&memories \\\\// Salt & Simon_Axis""",
    """E00200""",
    """Simon_Axis•騎士•StR-1""",
    """Arenn Saki as \"mAze\"""",
    """FORGET :: CLUTTER""",
    """XMT is silvery, 小咩兔 is silvery""",
]
